import type { ShopTemplateDefinition, ShopTemplateId } from "./types";

export const SHOP_TEMPLATES: ShopTemplateDefinition[] = [
  {
    id: "clean-guma",
    tier: "basic",
    label: "Clean Guma",
    description: "Mobile-first catalog with crisp cards and a friendly checkout flow.",
    mood: "Trusted · everyday · shoppable",
    tags: ["default", "food", "services"],
    previewGradient: "linear-gradient(145deg, #ecfdf5 0%, #059669 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "row",
    hero: "gradient",
    tokens: {
      primary: "#059669",
      accent: "#f59e0b",
      background: "#f4faf7",
      foreground: "#0f172a",
      card: "#ffffff",
      muted: "#64748b",
      border: "#d1fae5",
      mode: "light",
      radius: "1rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "mono-market",
    tier: "basic",
    label: "Mono Market",
    description: "High-contrast black & white layout with sharp type and zero clutter.",
    mood: "Minimal · premium · editorial",
    tags: ["fashion", "prints", "modern"],
    previewGradient: "linear-gradient(160deg, #ffffff 0%, #111827 85%)",
    minPlan: "free",
    layout: "classic",
    header: "minimal",
    card: "row",
    hero: "noise",
    tokens: {
      primary: "#111827",
      accent: "#6b7280",
      background: "#fafafa",
      foreground: "#111827",
      card: "#ffffff",
      muted: "#6b7280",
      border: "#e5e7eb",
      mode: "light",
      radius: "0.375rem",
      displayFont: "system",
    },
  },
  {
    id: "blush-bakery",
    tier: "basic",
    label: "Blush Bakery",
    description: "Soft pastels, rounded shapes, and warm vibes for cakes and sweets.",
    mood: "Cozy · IG-worthy · sweet",
    tags: ["bakery", "pastry", "gifts"],
    previewGradient: "linear-gradient(145deg, #fff1f2 0%, #fecdd3 55%, #fda4af 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "row",
    hero: "gradient",
    tokens: {
      primary: "#e11d48",
      accent: "#fb7185",
      background: "#fff7f8",
      foreground: "#4c0519",
      card: "#ffffff",
      muted: "#9f1239",
      border: "#fecdd3",
      mode: "light",
      radius: "1.25rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "simply-sweet",
    tier: "standard",
    label: "Simply Sweet",
    description:
      "Cream-and-neon home bakery layout with vlog teasers, glass product cards, and a dark creator dashboard.",
    mood: "Cozy · creator · home kitchen",
    tags: ["bakery", "pastry", "vlog", "home baking", "creator", "sweets"],
    previewGradient: "linear-gradient(145deg, #fffdf5 0%, #ffd1dc 45%, #ff007f 100%)",
    minPlan: "growth",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#FF007F",
      accent: "#FFD1DC",
      background: "#FFFDF5",
      foreground: "#2D1B1B",
      card: "rgba(255, 209, 220, 0.25)",
      muted: "#2D1B1B99",
      border: "#FFD1DC",
      mode: "light",
      radius: "1rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "neon-bazaar",
    tier: "standard",
    label: "Neon Bazaar",
    description: "Dark mode shop with electric accents — built for TikTok-era discovery.",
    mood: "Gen Z · night market · hype",
    tags: ["streetwear", "snacks", "viral"],
    previewGradient: "linear-gradient(135deg, #0f172a 0%, #7c3aed 50%, #22d3ee 100%)",
    minPlan: "growth",
    layout: "bento",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tokens: {
      primary: "#a855f7",
      accent: "#22d3ee",
      background: "#020617",
      foreground: "#f8fafc",
      card: "rgba(15, 23, 42, 0.72)",
      muted: "#94a3b8",
      border: "rgba(148, 163, 184, 0.25)",
      mode: "dark",
      radius: "1rem",
      displayFont: "mono-accent",
    },
  },
  {
    id: "street-cart",
    tier: "standard",
    label: "Street Cart",
    description: "Sticker collage energy, bold blocks, and loud CTAs like a pop-up stall.",
    mood: "Playful · bold · local",
    tags: ["food cart", "merch", "events"],
    previewGradient: "linear-gradient(145deg, #fef08a 0%, #f97316 45%, #dc2626 100%)",
    minPlan: "growth",
    layout: "hero-stack",
    header: "sticker",
    card: "brutal",
    hero: "gradient",
    tokens: {
      primary: "#ea580c",
      accent: "#facc15",
      background: "#fffbeb",
      foreground: "#1c1917",
      card: "#ffffff",
      muted: "#78716c",
      border: "#1c1917",
      mode: "light",
      radius: "0.5rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "magazine-rack",
    tier: "standard",
    label: "Magazine Rack",
    description: "Editorial grid with big imagery — perfect for lookbooks and curated drops.",
    mood: "Curated · aesthetic · lifestyle",
    tags: ["fashion", "skincare", "gifts"],
    previewGradient: "linear-gradient(160deg, #faf5ff 0%, #ddd6fe 50%, #c4b5fd 100%)",
    minPlan: "growth",
    layout: "editorial",
    header: "split",
    card: "magazine",
    hero: "photo",
    tokens: {
      primary: "#6d28d9",
      accent: "#c084fc",
      background: "#faf5ff",
      foreground: "#2e1065",
      card: "#ffffff",
      muted: "#7c3aed",
      border: "#e9d5ff",
      mode: "light",
      radius: "0.75rem",
      displayFont: "system",
    },
  },
  {
    id: "glass-future",
    tier: "advanced",
    label: "Glass Future",
    description: "Frosted glass layers, soft glow, and floating product tiles — iOS-meets-2030.",
    mood: "Futuristic · premium · sleek",
    tags: ["tech", "beauty", "premium"],
    previewGradient: "linear-gradient(145deg, #dbeafe 0%, #6366f1 50%, #ec4899 100%)",
    minPlan: "pro",
    layout: "immersive",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tokens: {
      primary: "#6366f1",
      accent: "#ec4899",
      background: "linear-gradient(180deg, #eef2ff 0%, #fdf2f8 100%)",
      foreground: "#1e1b4b",
      card: "rgba(255, 255, 255, 0.55)",
      muted: "#6366f1",
      border: "rgba(99, 102, 241, 0.2)",
      mode: "light",
      radius: "1.5rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "y2k-chrome",
    tier: "advanced",
    label: "Y2K Chrome",
    description: "Liquid chrome gradients, bubble UI, and retro-future nostalgia.",
    mood: "Y2K · playful · iconic",
    tags: ["merch", "beauty", "creator"],
    previewGradient: "linear-gradient(135deg, #fbcfe8 0%, #c4b5fd 35%, #67e8f9 70%, #fde68a 100%)",
    minPlan: "pro",
    layout: "bento",
    header: "sticker",
    card: "grid",
    hero: "chrome",
    tokens: {
      primary: "#8b5cf6",
      accent: "#06b6d4",
      background: "#fdf4ff",
      foreground: "#312e81",
      card: "rgba(255,255,255,0.85)",
      muted: "#7c3aed",
      border: "#ddd6fe",
      mode: "light",
      radius: "9999px",
      displayFont: "bricolage",
    },
  },
  {
    id: "holo-grid",
    tier: "advanced",
    label: "Holo Grid",
    description: "Holographic mesh, scanline accents, and floating cards — peak future shop.",
    mood: "Cyber · experimental · flagship",
    tags: ["limited drops", "gaming", "hype"],
    previewGradient: "linear-gradient(135deg, #020617 0%, #0891b2 40%, #d946ef 100%)",
    minPlan: "pro",
    layout: "immersive",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tokens: {
      primary: "#22d3ee",
      accent: "#e879f9",
      background: "#020617",
      foreground: "#ecfeff",
      card: "rgba(2, 6, 23, 0.65)",
      muted: "#67e8f9",
      border: "rgba(34, 211, 238, 0.25)",
      mode: "dark",
      radius: "1rem",
      displayFont: "mono-accent",
    },
  },
  {
    id: "bloom",
    tier: "standard",
    label: "Bloom",
    description:
      "Clean fashion & retail catalog with sticky header, product grid, and shoppable cards — ThemeWagon Bloom template.",
    mood: "Modern · retail · fashion-forward",
    tags: ["fashion", "retail", "footwear", "apparel", "catalog"],
    previewGradient: "linear-gradient(145deg, #fff7ed 0%, #ea580c 100%)",
    minPlan: "free",
    layout: "classic",
    header: "floating-glass",
    card: "grid",
    hero: "gradient",
    tokens: {
      primary: "#ea580c",
      accent: "#111827",
      background: "#ffffff",
      foreground: "#171717",
      card: "#ffffff",
      muted: "#737373",
      border: "#e5e5e5",
      mode: "light",
      radius: "1.225rem",
      displayFont: "system",
    },
  },
  {
    id: "sarab",
    tier: "standard",
    label: "Sarab",
    description:
      "Fast food & restaurant layout with hero, marquee, menu cards, and warm cream/red palette — ThemeWagon Sarab template.",
    mood: "Warm · restaurant · appetizing",
    tags: ["food", "restaurant", "catering", "fast-food", "menu"],
    previewGradient: "linear-gradient(145deg, #fff8f0 0%, #e8281a 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#e8281a",
      accent: "#f6a623",
      background: "#fff8f0",
      foreground: "#1a1a1a",
      card: "#ffffff",
      muted: "#666666",
      border: "#e5e5e5",
      mode: "light",
      radius: "1.125rem",
      displayFont: "system",
    },
  },
  {
    id: "furnish",
    tier: "standard",
    label: "Furnish",
    description:
      "Editorial furniture storefront with hero slider feel, product collection grid, and dark footer — ThemeWagon Furnish template.",
    mood: "Editorial · home · premium furniture",
    tags: ["furniture", "home", "interior", "decor", "living"],
    previewGradient: "linear-gradient(160deg, #f6f5f4 0%, #211f1c 85%)",
    minPlan: "free",
    layout: "editorial",
    header: "minimal",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#111100",
      accent: "#d47f31",
      background: "#ffffff",
      foreground: "#211f1c",
      card: "#ffffff",
      muted: "#837a6d",
      border: "#ecebe9",
      mode: "light",
      radius: "0",
      displayFont: "system",
    },
  },
  {
    id: "zay",
    tier: "standard",
    label: "Zay Shop",
    description:
      "General retail eCommerce layout with green accent, hero carousel, category circles, and featured product cards — TemplateMo Zay Shop.",
    mood: "Clean · retail · catalog",
    tags: ["retail", "general", "shop", "catalog", "market"],
    previewGradient: "linear-gradient(160deg, #e9eef5 0%, #59ab6e 55%, #212934 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#59ab6e",
      accent: "#212934",
      background: "#ffffff",
      foreground: "#212934",
      card: "#ffffff",
      muted: "#bcbcbc",
      border: "#e9eef5",
      mode: "light",
      radius: "0.375rem",
      displayFont: "system",
    },
  },
  {
    id: "electro",
    tier: "standard",
    label: "Electro",
    description:
      "Electronics eCommerce layout with orange accent, mega search header, category nav, hero carousel, and product tabs — Electro Bootstrap template.",
    mood: "Tech · gadgets · marketplace",
    tags: ["electronics", "gadgets", "phones", "laptops", "tech"],
    previewGradient: "linear-gradient(160deg, #fff5eb 0%, #F28B00 50%, #F92400 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#F28B00",
      accent: "#F92400",
      background: "#ffffff",
      foreground: "#484848",
      card: "#ffffff",
      muted: "#6c757d",
      border: "#e9ecef",
      mode: "light",
      radius: "0.5rem",
      displayFont: "system",
    },
  },
  {
    id: "kaira",
    tier: "standard",
    label: "Kaira",
    description:
      "Editorial fashion storefront with collection hero, category banners, product carousels, and sage accent — TemplatesJungle Kaira template.",
    mood: "Editorial · fashion · boutique",
    tags: ["fashion", "apparel", "clothing", "boutique", "style"],
    previewGradient: "linear-gradient(160deg, #F1F1F0 0%, #8C907E 70%, #111111 100%)",
    minPlan: "free",
    layout: "editorial",
    header: "minimal",
    card: "magazine",
    hero: "photo",
    tokens: {
      primary: "#8C907E",
      accent: "#111111",
      background: "#ffffff",
      foreground: "#111111",
      card: "#ffffff",
      muted: "#8f8f8f",
      border: "#F1F1F0",
      mode: "light",
      radius: "0",
      displayFont: "bricolage",
    },
  },
  {
    id: "foodmart",
    tier: "standard",
    label: "FoodMart",
    description:
      "Grocery eCommerce layout with yellow accent, mega search, hero banners, categories, and product tabs — TemplatesJungle FoodMart.",
    mood: "Fresh · grocery · everyday essentials",
    tags: ["grocery", "supermarket", "food", "mart", "fresh"],
    previewGradient: "linear-gradient(160deg, #FFF9EB 0%, #FFC43F 50%, #6995B1 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#FFC43F",
      accent: "#6995B1",
      background: "#ffffff",
      foreground: "#212529",
      card: "#ffffff",
      muted: "#6c757d",
      border: "#eef1f3",
      mode: "light",
      radius: "1rem",
      displayFont: "system",
    },
  },
  {
    id: "stylish",
    tier: "standard",
    label: "Stylish",
    description:
      "Bold shoe & apparel storefront with hero banners, coupon strip, hover product cards, and collection spots — TemplatesJungle Stylish.",
    mood: "Bold · footwear · streetwear",
    tags: ["shoes", "footwear", "sneakers", "apparel", "fashion"],
    previewGradient: "linear-gradient(160deg, #F1F1F0 0%, #ce071e 55%, #111111 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#ce071e",
      accent: "#111111",
      background: "#ffffff",
      foreground: "#111111",
      card: "#ffffff",
      muted: "#8f8f8f",
      border: "#F1F1F0",
      mode: "light",
      radius: "0",
      displayFont: "system",
    },
  },
  {
    id: "mellow",
    tier: "standard",
    label: "Mellow",
    description:
      "Elegant hotel & resort layout with booking hero, room cards, gallery, and amenities grid — TemplatesJungle Mellow.",
    mood: "Serene · hospitality · retreat",
    tags: ["hotel", "resort", "hospitality", "accommodation", "staycation"],
    previewGradient: "linear-gradient(160deg, #F9F6F3 0%, #D16806 55%, #1A1A1A 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "magazine",
    hero: "photo",
    tokens: {
      primary: "#D16806",
      accent: "#1A1A1A",
      background: "#ffffff",
      foreground: "#353535",
      card: "#F9F6F3",
      muted: "#777F81",
      border: "#EAE5DD",
      mode: "light",
      radius: "1.25rem",
      displayFont: "bricolage",
    },
  },
  {
    id: "organic",
    tier: "standard",
    label: "Organic",
    description:
      "Fresh farm produce storefront with search header, hero stats, category carousel, and product tabs — TemplatesJungle Organic.",
    mood: "Fresh · farm · natural",
    tags: ["organic", "farm", "produce", "vegetables", "healthy"],
    previewGradient: "linear-gradient(160deg, #FFF9EB 0%, #6BB252 55%, #364127 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#6BB252",
      accent: "#364127",
      background: "#ffffff",
      foreground: "#333333",
      card: "#ffffff",
      muted: "#747474",
      border: "#F7F7F7",
      mode: "light",
      radius: "0.75rem",
      displayFont: "system",
    },
  },
  {
    id: "waggy",
    tier: "standard",
    label: "Waggy",
    description:
      "Pet lover storefront with search header, hero, icon categories, tabbed products, and services strip — TemplatesJungle Waggy.",
    mood: "Warm · playful · pet-friendly",
    tags: ["pet", "pets", "dog", "cat", "supplies"],
    previewGradient: "linear-gradient(160deg, #F9F3EC 0%, #DEAD6F 55%, #333333 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#DEAD6F",
      accent: "#333333",
      background: "#ffffff",
      foreground: "#333333",
      card: "#F9F3EC",
      muted: "#747474",
      border: "#eeeeee",
      mode: "light",
      radius: "0.75rem",
      displayFont: "system",
    },
  },
  {
    id: "fruitables",
    tier: "standard",
    label: "Fruitables",
    description:
      "Bright fruits & vegetables storefront with top bar, hero search, feature strip, tabbed products, promos, and banner — HTML Codex Fruitables.",
    mood: "Fresh · colorful · market",
    tags: ["fruit", "vegetable", "produce", "organic", "fresh"],
    previewGradient: "linear-gradient(160deg, #F4F6F8 0%, #81C408 50%, #FFB524 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#81C408",
      accent: "#FFB524",
      background: "#ffffff",
      foreground: "#45595B",
      card: "#F4F6F8",
      muted: "#6c757d",
      border: "#FFB524",
      mode: "light",
      radius: "0.75rem",
      displayFont: "system",
    },
  },
  {
    id: "ministore",
    tier: "standard",
    label: "MiniStore",
    description:
      "Clean gadgets storefront with hero billboard, service icons, product carousels, and sale banner — MiniStore template.",
    mood: "Minimal · tech · modern",
    tags: ["electronics", "gadgets", "phones", "watches", "tech"],
    previewGradient: "linear-gradient(160deg, #EDF1F3 0%, #72AEC8 55%, #212529 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#72AEC8",
      accent: "#212529",
      background: "#ffffff",
      foreground: "#212529",
      card: "#F3F3F3",
      muted: "#AEAEAE",
      border: "#D8D8D8",
      mode: "light",
      radius: "0",
      displayFont: "system",
    },
  },
  {
    id: "aircon",
    tier: "standard",
    label: "AirCon",
    description:
      "HVAC & AC repair service storefront with quote hero, service grid, bookable packages, and free quote form — ThemeWagon AirCon.",
    mood: "Cool · trustworthy · service-ready",
    tags: ["hvac", "aircon", "ac repair", "cooling", "heating", "service"],
    previewGradient: "linear-gradient(160deg, #0D1B2A 0%, #FF800F 55%, #ffffff 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#FF800F",
      accent: "#0D1B2A",
      background: "#ffffff",
      foreground: "#0D1B2A",
      card: "#F8F9FA",
      muted: "#6c757d",
      border: "#E9ECEF",
      mode: "light",
      radius: "0.5rem",
      displayFont: "system",
    },
  },
  {
    id: "carserv",
    tier: "standard",
    label: "CarServ",
    description:
      "Auto repair storefront with booking hero, service tabs, parts & labor packages, and quote form — ThemeWagon CarServ.",
    mood: "Bold · garage · reliable",
    tags: ["auto", "car repair", "garage", "mechanic", "parts", "service"],
    previewGradient: "linear-gradient(160deg, #1B1B1B 0%, #D81324 55%, #ffffff 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#D81324",
      accent: "#1B1B1B",
      background: "#ffffff",
      foreground: "#1B1B1B",
      card: "#F5F5F5",
      muted: "#6c757d",
      border: "#DEE2E6",
      mode: "light",
      radius: "0.35rem",
      displayFont: "system",
    },
  },
  {
    id: "motto",
    tier: "standard",
    label: "Motto Moto",
    description:
      "Motorcycle & moto gear ecommerce with bold black/white hero, category strip, and product grid — ThemeWagon Motto.",
    mood: "Bold · street · moto",
    tags: ["motorcycle", "moto", "gear", "helmet", "bike", "retail"],
    previewGradient: "linear-gradient(160deg, #000000 0%, #E10600 55%, #ffffff 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#E10600",
      accent: "#000000",
      background: "#ffffff",
      foreground: "#000000",
      card: "#F9F9F9",
      muted: "#6c757d",
      border: "#E5E5E5",
      mode: "light",
      radius: "0",
      displayFont: "system",
    },
  },
  {
    id: "studio",
    tier: "standard",
    label: "Studio",
    description:
      "Photography & creative packages with portfolio hero, session booking, and print/signage interim — ThemeWagon Studio.",
    mood: "Creative · portfolio · premium",
    tags: ["photography", "studio", "creative", "print", "signage", "sessions"],
    previewGradient: "linear-gradient(160deg, #1d1d1d 0%, #838383 55%, #f6f6f6 100%)",
    minPlan: "free",
    layout: "editorial",
    header: "minimal",
    card: "magazine",
    hero: "photo",
    tokens: {
      primary: "#1d1d1d",
      accent: "#838383",
      background: "#ffffff",
      foreground: "#1d1d1d",
      card: "#f6f6f6",
      muted: "#838383",
      border: "#dcdcdc",
      mode: "light",
      radius: "0",
      displayFont: "system",
    },
  },
  {
    id: "haircut",
    tier: "standard",
    label: "HairCut Salon",
    description:
      "Barbershop & salon storefront with dark appointment hero, service grid, and pricing plan — ThemeWagon HairCut.",
    mood: "Bold · barber · appointment-ready",
    tags: ["barber", "salon", "haircut", "grooming", "beauty", "appointment"],
    previewGradient: "linear-gradient(160deg, #000000 0%, #EB1616 55%, #191C24 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tokens: {
      primary: "#EB1616",
      accent: "#191C24",
      background: "#000000",
      foreground: "#ffffff",
      card: "#191C24",
      muted: "#6C7293",
      border: "#2a2f3a",
      mode: "dark",
      radius: "0",
      displayFont: "system",
    },
  },
  {
    id: "specialty",
    tier: "standard",
    label: "Specialty",
    description:
      "Single-offer specialty storefront that spotlights one hero product or service, with optional supporting items.",
    mood: "Focused · conversion · specialty",
    tags: ["specialty", "single product", "flagship", "service", "hero offer"],
    previewGradient: "linear-gradient(160deg, #f4f7f6 0%, #0f766e 55%, #134e4a 100%)",
    minPlan: "free",
    layout: "hero-stack",
    header: "minimal",
    card: "row",
    hero: "photo",
    tokens: {
      primary: "#0f766e",
      accent: "#134e4a",
      background: "#f4f7f6",
      foreground: "#102a27",
      card: "#ffffff",
      muted: "#5b726e",
      border: "#d5e0dd",
      mode: "light",
      radius: "0.75rem",
      displayFont: "system",
    },
  },
  {
    id: "palenke",
    tier: "basic",
    label: "Palenke",
    description:
      "Bright, friendly shop: a gradient banner in your colour, category chips, and big product cards with Details and Add to basket.",
    mood: "Bright · friendly · mobile-first",
    tags: ["palenke", "everyday", "food", "bright", "mobile-first"],
    previewGradient: "linear-gradient(120deg, #4f46e5 0%, #6d28d9 60%, #312e81 100%)",
    minPlan: "free",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "gradient",
    tokens: {
      primary: "#4f46e5",
      accent: "#7c3aed",
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      muted: "#64748b",
      border: "#e2e8f0",
      mode: "light",
      radius: "1.5rem",
      displayFont: "system",
    },
  },
];

export const SHOP_TEMPLATE_MAP = Object.fromEntries(
  SHOP_TEMPLATES.map((template) => [template.id, template])
) as Record<ShopTemplateId, ShopTemplateDefinition>;

export function getShopTemplate(id: ShopTemplateId): ShopTemplateDefinition {
  return SHOP_TEMPLATE_MAP[id];
}

export function normalizeShopTemplateId(value: string): string {
  return value;
}

export function isShopTemplateId(value: string): value is ShopTemplateId {
  return value in SHOP_TEMPLATE_MAP;
}

export function listShopTemplatesByTier(tier?: ShopTemplateDefinition["tier"]) {
  if (!tier) return SHOP_TEMPLATES;
  return SHOP_TEMPLATES.filter((template) => template.tier === tier);
}

export const TIER_LABELS: Record<ShopTemplateDefinition["tier"], string> = {
  basic: "Basic",
  standard: "Standard",
  advanced: "Advanced",
};

export const TIER_DESCRIPTIONS: Record<ShopTemplateDefinition["tier"], string> = {
  basic: "Clean, fast, and perfect for getting live quickly.",
  standard: "Bold Gen Z layouts with more personality and motion-ready structure.",
  advanced: "Futuristic flagship designs for brands that want to stand out.",
};
