export { db, getDb, closeDb, type Database } from "./client";
export { getDatabaseUrl, isNeonDatabase } from "./env";
export {
  getTenantStorefrontBySlug,
  getTenantStorefrontPreviewBySlug,
  getPendingTenantBySlug,
  getTenantAvailabilityBySlug,
  getTenantStatusById,
  type StorefrontTenantRecord,
  type StorefrontVariant,
  type PendingTenantRecord,
} from "./queries/storefront";
export {
  getProductVariantsForTenant,
  saveProductVariants,
  listActiveVariantsForProducts,
  variantTitleOf,
  combinationsOf,
  normalizeOptions,
  VariantError,
  MAX_OPTIONS,
  MAX_OPTION_VALUES,
  MAX_VARIANTS,
  type ProductOption,
  type VariantRow,
  type VariantInput,
  type ProductVariantsView,
} from "./queries/variants";
export {
  DEFAULT_LOW_STOCK_THRESHOLD,
  lowStockThresholdOf,
  getLowStockThreshold,
  listInventory,
  getLowStockSummary,
  applyStockChanges,
  inventoryToCsv,
  parseCsv,
  planInventoryCsvImport,
  INVENTORY_CSV_HEADERS,
  InventoryError,
  type InventoryRow,
  type LowStockSummary,
  type StockChange,
  type StockChangeResult,
  type CsvImportPlan,
} from "./queries/inventory";
export {
  listTeam,
  createStaffInvite,
  revokeStaffInvite,
  getStaffInvite,
  acceptStaffInvite,
  changeStaffRole,
  removeStaff,
  setStaffPin,
  getInviteAccount,
  posStaffIdForUser,
  countOpenInvites,
  StaffError,
  INVITE_TTL_DAYS,
  MAX_STAFF,
  STAFF_ROLE_VALUES,
  type TeamMember,
  type PendingInvite,
  type InviteView,
} from "./queries/staff";
export {
  updateOrderNotes,
  listOrderTags,
  normalizeTags,
  getAfterSaleView,
  editOrderItems,
  recordReturn,
  voidPosSale,
  shiftRefundsByMethod,
  REFUND_METHODS,
  MAX_TAGS,
  type AfterSaleView,
  type AfterSaleLine,
  type EditLineInput,
  type EditResult,
  type ReturnInput,
  type ReturnItemInput,
  type ReturnResult,
  type RefundMethod,
  type VoidResult,
  type GatewayPartialRefund,
} from "./queries/after-sale";
export {
  BIR_REQUIRED,
  birMissing,
  birActive,
  formatInvoiceNumber,
  getXReading,
  createZReading,
  listZReadings,
  zReadingStatus,
  posEJournalCsv,
  getBirReceiptHeader,
  BirError,
  type ReadingTotals,
  type XReading,
  type ZReading,
} from "./queries/bir";
export {
  GumaIdError,
  normalizeBuyerPhone,
  createBuyerOtp,
  verifyBuyerOtp,
  getBuyer,
  updateBuyerProfile,
  bumpBuyerSession,
  listBuyerAddresses,
  saveBuyerAddress,
  deleteBuyerAddress,
  listBuyerOrders,
  linkOrderToBuyer,
  listBuyerShops,
  setBuyerShopReminders,
  exportBuyerData,
  deleteBuyerAccount,
  gumaIdShare,
  OTP_TTL_MINUTES,
  MAX_ADDRESSES,
  type BuyerAccount,
  type BuyerAddress,
  type BuyerOrder,
  type BuyerShopPrefs,
  type BuyerAddressJson,
} from "./queries/guma-id";
export { logActivity, listActivity, orderNumberFor, productSnapshot, type ActivityActor, type ActivityInput, type ActivityRow } from "./queries/activity";
export {
  classifyTenantPublicAccess,
  isTenantAcceptingOrders,
  isTenantSellerWritable,
  checkoutHttpRejectionForStatus,
  sellerWriteHttpRejectionForStatus,
  TENANT_SUSPENDED_BUYER_MESSAGE,
  TENANT_SUSPENDED_SELLER_MESSAGE,
  TENANT_PENDING_BUYER_MESSAGE,
  type TenantLifecycleStatus,
  type TenantPublicAccess,
} from "./tenant-access";
export {
  getTenantDashboard,
  activateTenantShop,
  tryAutoActivateTenant,
  type TenantDashboardData,
  type SetupStep,
} from "./queries/tenant-dashboard";
export {
  listCustomersForTenant,
  getCustomerForTenant,
  getCustomerStatsForTenant,
  type CustomerSummary,
  type CustomerDetail,
  type CustomerStats,
} from "./queries/customers";
export {
  getPlatformSetting,
  setPlatformSetting,
  getActiveLanding,
  parseActiveLanding,
  ACTIVE_LANDINGS,
  setActiveLanding,
  getPlatformOpsSettings,
  updatePlatformOpsSettings,
  parseTriFlag,
  triFlagToBoolOverride,
  ACTIVE_LANDING_KEY,
  SOFT_LAUNCH_KEY,
  FREE_TEMPLATE_SWITCH_KEY,
  TEMPLATE_SWITCH_REQUIRES_UPGRADE_KEY,
  PAYMENTS_MODE_KEY,
  HELPDESK_NOTIFY_EMAIL_KEY,
  SUPPORT_CONTACT_EMAIL_KEY,
  type ActiveLanding,
  type TriFlag,
  type PlatformPaymentsMode,
  type PlatformOpsSettings,
} from "./queries/platform-settings";
export {
  ensureShopCategoriesSeeded,
  syncMissingShopCategories,
  listShopBusinessCategories,
  listOnboardingCategoryLabels,
  listOnboardingCategoryGroups,
  upsertShopBusinessCategory,
  setShopCategoryStatus,
  listTemplateStock,
  getTemplateStockByKey,
  createTemplateStock,
  setTemplateStockStatus,
  updateTemplateStockLabel,
  renameGenericLookStockLabels,
  countPublishedStockByCategory,
  recordTemplateIntelligenceEvent,
  listRecentTemplateIntelligenceEvents,
  slugifyShopCategory,
  type ShopBusinessCategoryRow,
  type TemplateStockRow,
  type ShopCategoryStatus,
  type TemplateStockStatus,
  type TemplateStockSource,
  type OnboardingCategoryGroup,
} from "./queries/template-intelligence";
export {
  createSupportTicket,
  listSupportTickets,
  getSupportTicketCounts,
  getSupportTicketById,
  addSupportTicketMessage,
  updateSupportTicket,
  type CreateSupportTicketInput,
  type SupportTicketListItem,
  type SupportTicketDetail,
  type SupportTicketStatus,
  type SupportTicketPriority,
  type SupportTicketChannel,
  type SupportRequesterType,
} from "./queries/support-tickets";
export {
  getTenantStorefrontSettings,
  updateTenantStorefront,
  type TenantStorefrontSettings,
  type UpdateTenantStorefrontInput,
} from "./queries/tenant-storefront";
export {
  getTenantSettings,
  updateTenantSettings,
  setTenantPaymentsMode,
  type TenantSettingsJson,
  type TenantSettingsRecord,
  type UpdateTenantSettingsInput,
} from "./queries/tenant-settings";
export {
  listProductsForTenant,
  getProductForTenant,
  createProductForTenant,
  updateProductForTenant,
  deleteProductForTenant,
  isProductSlugAvailable,
  slugFromProductTitle,
  normalizeProductSlug,
  type ProductListItem,
  type CreateProductInput,
  type UpdateProductInput,
  type DeleteProductResult,
} from "./queries/products";
export {
  createCategoryForTenant,
  deleteCategoryForTenant,
  isCategorySlugAvailable,
  listCategoriesForTenant,
  slugFromCategoryName,
  type CategoryListItem,
} from "./queries/categories";
export {
  getRawAiUsageCounts,
  recordAiUsage,
  getTenantOwnerContact,
  type RawAiUsageCounts,
} from "./queries/ai-usage";
export {
  createOrderForTenant,
  getOrderForTracking,
  getOrderPaymentForRefund,
  listOrdersForTenant,
  getPackingSlips,
  type PackingSlip,
  markOrderPaidByIntent,
  markPaymentFailedByIntent,
  recordPaymentIntent,
  OrderError,
  ORDER_STATUS_TRANSITIONS,
  type CreateOrderInput,
  type CreatedOrder,
  type MarkOrderPaidResult,
  type OrderRefundInfo,
  type OrderStatus,
  type OrderTrackingData,
  type OrderTrackingDelivery,
  type TenantOrderListItem,
} from "./queries/orders";
export {
  applyOrderAction,
  factsOf,
  refundOrder,
  expireUnpaidOrders,
  restockOrderInTx,
  DEFAULT_UNPAID_EXPIRY_HOURS,
  MIN_UNPAID_EXPIRY_HOURS,
  MAX_UNPAID_EXPIRY_HOURS,
  type ApplyOrderActionInput,
  type ApplyOrderActionResult,
  type GatewayRefundRequest,
  type RefundOrderResult,
  type RestockReason,
} from "./queries/order-lifecycle";
export {
  planOrderAction,
  invariantViolation,
  legacyStatusOf,
  legacyPaymentStatusOf,
  orderBucketOf,
  bookingBlockedReason,
  describeStates,
  ORDER_BUCKET_LABELS,
  ORDER_STATES,
  PAYMENT_STATES,
  FULFILLMENT_STATES,
  type OrderState,
  type PaymentState,
  type FulfillmentState,
  type OrderFacts,
  type OrderAction,
  type ActionSource,
  type OrderBucket,
  type PlanResult,
} from "./queries/order-state";
export {
  insertOutboxEvent,
  relayOutbox,
  outboxBacklog,
  OUTBOX_MAX_ATTEMPTS,
  type OutboxRow,
  type RelayResult,
} from "./queries/outbox";
export { getDefaultLocation, getDefaultLocationId, type LocationRow } from "./queries/locations";
export {
  persistDomainEvent,
  listDomainEventsForTenant,
  type DomainEventRow,
} from "./queries/domain-events";
export {
  PLAN_PRICES_PHP,
  PLAN_PERIOD_DAYS,
  createPlanPayment,
  markPlanPaymentPaidByIntent,
  type CreatePlanPaymentInput,
  type MarkPlanPaymentPaidResult,
} from "./queries/plan-billing";
export {
  SELLER_PLANS,
  PLATFORM_PLANS as PLAN_CATALOG,
  getSellerPlan,
  normalizePlanId,
  planPriceMonthly,
  type PlanDefinition,
  type SubscriptionPlanId,
} from "./plans";
export {
  getLaunchTenantState,
  updateStoreDna,
  saveThemeDraft,
  publishThemeDraft,
  resolvePublishedThemeJson,
  needsGumaLaunch,
  resolveSellerHomePath,
  listRecentTemplateIdsByCategory,
  type LaunchTenantState,
  type ThemeJson,
  type StoreDnaJson,
} from "./queries/launch";
export {
  createChangeRequest,
  submitChangeRequest,
  approveChangeRequest,
  rejectChangeRequest,
  getChangeRequest,
  listChangeRequestsForTenant,
  writeTenantAudit,
  listTenantAudit,
  publishThemeChangeRequest,
  publishCatalogChangeRequest,
  publishPricingChangeRequest,
  publishSeoChangeRequest,
  rollbackSeoChangeRequest,
  publishCheckoutChangeRequest,
  rollbackCheckoutChangeRequest,
  publishShippingChangeRequest,
  rollbackShippingChangeRequest,
  markChangeRequestPublished,
  publishStorefrontWithApproval,
  rollbackThemeChangeRequest,
  type ChangeRequestRow,
  type ChangeRequestDomain,
  type ChangeRequestStatus,
  type ActorType,
  type CatalogListingProposal,
  type PricingProposal,
} from "./queries/change-requests";
export {
  getTenantSeoState,
  saveTenantSeoDraft,
  publishTenantSeo,
  buildDefaultSeo,
  normalizeSeoJson,
  EMPTY_SEO,
  type TenantSeoJson,
  type TenantSeoState,
} from "./queries/seo";
export {
  getTenantCheckoutState,
  saveTenantCheckoutDraft,
  publishTenantCheckout,
  getPublishedCheckoutForSlug,
  upsertCheckoutSession,
  markCheckoutSessionConverted,
  checkoutSessionExists,
  abandonStaleCheckoutSessions,
  normalizeCheckoutJson,
  checkoutFromLegacySettings,
  computeCheckoutTotals,
  findActiveCoupon,
  isPaymentMethodEnabled,
  EMPTY_CHECKOUT,
  type TenantCheckoutJson,
  type TenantCheckoutState,
} from "./queries/checkout";
export type { CheckoutTotals } from "./types/tenant-checkout";
export {
  getTenantShippingState,
  saveTenantShippingDraft,
  publishTenantShipping,
  getPublishedShippingForSlug,
  normalizeShippingJson,
  shippingFromLegacyDelivery,
  legacyDeliveryFromShipping,
  resolveShippingFee,
  isPickupEnabled,
  EMPTY_SHIPPING,
  type TenantShippingJson,
  type TenantShippingState,
} from "./queries/shipping";
export {
  savePushSubscription,
  deletePushSubscription,
  deletePushSubscriptions,
  listPushSubscriptionsForTenant,
  type SavePushSubscriptionInput,
  type TenantPushSubscription,
} from "./queries/push-subscriptions";
export {
  recordDeliveryQuote,
  createDeliveryBooking,
  updateDeliveryByProviderOrderId,
  applyCourierFulfillmentUpdate,
  getDeliveryForOrder,
  getOrderForDeliveryBooking,
  upsertManualDeliveryForOrder,
  type RecordDeliveryQuoteInput,
  type CreateDeliveryBookingInput,
  type DeliveryStatusPatch,
  type OrderDeliveryInfo,
  type OrderForDeliveryBooking,
  type UpsertManualDeliveryInput,
} from "./queries/deliveries";
export {
  getOrderInsightsLast7d,
  getProductById,
  pickFeaturedProductId,
  type OrderInsights7d,
} from "./queries/order-insights";
export {
  listContentQueue,
  createContentQueueItem,
  updateContentQueueStatus,
  startAgentRun,
  finishAgentRun,
  listRecentAgentRuns,
  listActiveTenantsForAgents,
  saveShopChatMessage,
  listShopChatMessages,
  listShopChatSessions,
  getTenantIdBySlug,
  resolveAgentSettings,
  resolveShopAssistantSettings,
  DEFAULT_AGENT_SETTINGS,
  DEFAULT_SHOP_ASSISTANT,
  type ContentQueueItem,
  type AgentSettings,
  type ShopAssistantSettings,
} from "./queries/agents";
export {
  resolveTenantPaymentsSettings,
  recordManualPaymentIntent,
  submitManualPaymentReference,
  confirmManualOrderPayment,
  rejectManualPaymentProof,
  getManualPaymentMetaForOrder,
  type PaymentsReceivingAccounts,
  type TenantPaymentsSettings,
} from "./queries/manual-payments";
export {
  PLATFORM_PLANS,
  TENANT_STATUSES,
  USER_STATUSES,
  getPlanById,
  planPrice,
  getPlatformStats,
  getPlatformAttention,
  getSignupSeries,
  getRevenueSeries,
  listTenants,
  getTenantDetail,
  setTenantStatus,
  setTenantPlan,
  listUsers,
  getUserRoleCounts,
  setUserStatus,
  setUserRole,
  listModerationQueue,
  getModerationCounts,
  moderateContentItem,
  listPlatformOrders,
  writeAudit,
  listAuditLog,
  type PlatformPlan,
  type TenantStatus,
  type UserStatus,
  type PlatformStats,
  type PlatformAttention,
  type DailyPoint,
  type TenantListItem,
  type ListTenantsFilters,
  type TenantDetail,
  type UserListItem,
  type ListUsersFilters,
  type ModerationItem,
  type ListModerationFilters,
  type ModerateInput,
  type PlatformOrderItem,
  type AuditEntry,
  type AuditLogItem,
} from "./queries/platform";
export {
  getWalletSummary,
  listWalletLedger,
  listTenantPayouts,
  requestTenantPayout,
  runWalletSettlement,
  processQueuedPayouts,
  resolveWalletSettings,
  creditSaleForOrder,
  WalletError,
  walletPayoutsEnabled,
  type TenantWalletSummary,
  type WalletLedgerItem,
  type TenantPayoutItem,
  type TenantWalletSettings,
} from "./queries/wallet";
export {
  PLATFORM_FEE_PERCENT,
  PLATFORM_FEE_FIXED_PHP,
  computePlatformFeeCentavos,
  computeSellerNetCentavos,
  walletClearanceHours,
  minAutoPayoutCentavos,
} from "./wallet-fees";
export {
  getLatestKycSession,
  getActiveKycSession,
  getOrCreateActiveKycSession,
  getKycSessionByToken,
  getKycSessionById,
  updateKycSession,
  upsertKycDocument,
  submitKycSession,
  reviewKycSession,
  isTenantKycApproved,
  validateKycSubmission,
  getKycDocumentStorageKey,
  getKycDocumentByToken,
  KycValidationError,
  type KycSessionRecord,
  type KycDocumentRecord,
  type KycStatus,
  type KycIdPath,
  type KycDocType,
} from "./queries/kyc";
export {
  countPhLocations,
  searchPhLocations,
  type PhLocationKind,
  type PhLocationSuggestion,
} from "./queries/ph-locations";
export * from "./schema/index";
export {
  recordStockMovement,
  listStockMovementsForProduct,
  type StockMovementItem,
  type StockMovementReason,
} from "./queries/stock-ledger";
export {
  sendWithLog,
  isOptedOut,
  addOptOut,
  normalizePhone,
  messageIdempotencyKey,
  listMessagesForOrder,
  listOptOuts,
  removeOptOut,
  listRecentMessages,
  type OptOutItem,
  type PlatformMessageItem,
  type MessageEntry,
  type ProviderSendResult,
  type SendWithLogResult,
  type MessageLogItem,
} from "./queries/message-log";
export {
  CHECKOUT_LINK_DELIVERY_MODES,
  CHECKOUT_LINK_MAX_ITEMS,
  CHECKOUT_LINK_PAYMENT_LABELS,
  CHECKOUT_LINK_PAYMENT_METHODS,
  CHECKOUT_LINK_SHARE_CHANNELS,
  CheckoutLinkError,
  checkoutLinkStatus,
  createCheckoutLink,
  bumpCheckoutLinkCounter,
  generateCheckoutLinkCode,
  getCheckoutLinkByCode,
  getCheckoutLinkForTenant,
  getCheckoutLinkShopOptions,
  isCheckoutLinkCode,
  listCheckoutLinksForTenant,
  resolveCheckoutLinkShopOptions,
  updateCheckoutLink,
  type CheckoutLinkDeliveryMode,
  type CheckoutLinkItemSummary,
  type CheckoutLinkPaymentMethod,
  type CheckoutLinkShareChannel,
  type CheckoutLinkShopOptions,
  type CheckoutLinkStatus,
  type CheckoutLinkSummary,
  type CreateCheckoutLinkInput,
  type PublicCheckoutLink,
  type UpdateCheckoutLinkInput,
} from "./queries/checkout-links";
export {
  SELL_CHANNELS,
  OnboardingError,
  finishOnboarding,
  getOnboardingState,
  markOnboardingStep,
  needsOnboarding,
  normalizeChatUrl,
  normalizePhMobile,
  saveBusinessProfile,
  saveOnboardingPayments,
  type OnboardingPaymentsInput,
  type OnboardingState,
  type OnboardingStep,
} from "./queries/onboarding";
export { getSellerToday, manilaStartOfDay, type SellerToday } from "./queries/seller-today";
export {
  claimRecoveryStep,
  describeRecoveryCart,
  getAutomationSummary,
  getOrderMessagingContext,
  getOrderEmailDetails,
  listRecoveryCandidates,
  listTenantMessages,
  listUnpaidReminderCandidates,
  RECOVERY_STEP_DELAYS_MINUTES,
  UNPAID_REMINDER_AFTER_HOURS,
  type AutomationSummary,
  type OrderMessagingContext,
  type RecoveryCandidate,
  type TenantMessageItem,
} from "./queries/automations";
export type { AutomationRecipeId, TenantAutomationSettings } from "./types/tenant-settings";
export {
  closeShift,
  createPosSale,
  createPosStaff,
  ensureRegister,
  getOpenShift,
  getPosReceipt,
  getPosStaffForAuth,
  getShiftSummary,
  listPosProducts,
  listPosStaff,
  listRecentShifts,
  listShiftSales,
  openShift,
  PIN_LOCK_MINUTES,
  PIN_MAX_ATTEMPTS,
  PosError,
  recordPinFailure,
  recordPinSuccess,
  updatePosStaff,
  type PosMeta,
  type PosProduct,
  type PosReceipt,
  type PosRegister,
  type PosSaleInput,
  type PosSaleListItem,
  type PosShift,
  type PosStaffRow,
  type ShiftSummary,
  type TenderTotals,
  type PosOfflineInfo,
  clampRungAt,
  refreshClosedShift,
} from "./queries/pos";
export {
  OFFLINE_BLOCK_SIZE,
  PosOfflineError,
  getOrReserveInvoiceBlock,
  listInvoiceBlocks,
  releaseInvoiceBlock,
  listSyncIssues,
  countOpenSyncIssues,
  resolveSyncIssue,
  recordRejectedOfflineSale,
  type InvoiceBlock,
  type InvoiceBlockRow,
  type PosSyncIssue,
} from "./queries/pos-offline";
export * from "./types/pos-tax";
export { getPlatformMetrics, type PlatformMetrics } from "./queries/platform-metrics";

// Phase 13 — channels
export * from "./types/sales-channel";
export {
  InboxError,
  META_REPLY_WINDOW_MS as SOCIAL_REPLY_WINDOW_MS,
  beginSocialSend,
  canReplyNow,
  countUnreadSocialThreads,
  disconnectSocialAccount,
  findSocialAccountByExternal,
  finishSocialSend,
  getSocialAccountForSend,
  getSocialThread,
  listSocialAccounts,
  listSocialThreads,
  markSocialAccountError,
  markSocialThreadRead,
  recordSocialMessage,
  setSocialThreadStatus,
  threadsForOrders,
  upsertSocialAccount,
  getChatProductCard,
  setSocialMessageContent,
  getChatCheckoutLink,
  ensureDemoSocialAccount,
  type ChatProductCard,
  type IncomingSocialMessage,
  type SocialAccountRow,
  type SocialMessageRow,
  type SocialThreadDetail,
  type SocialThreadRow,
} from "./queries/social-inbox";
export {
  MarketplaceSyncError,
  disconnectMarketplaceAccount,
  getMarketplaceAccount,
  importMarketplaceOrder,
  linkMarketplaceListing,
  listImportedOrders,
  listMarketplaceAccounts,
  listMarketplaceListings,
  listSyncingMarketplaceAccounts,
  marketplaceStockPushPlan,
  mirrorCatalogAsListings,
  recordStockPush,
  salesByChannel,
  saveMarketplaceListings,
  updateMarketplaceAccount,
  upsertMarketplaceAccount,
  type ImportResult,
  type ImportedOrderInput,
  type ListingRow,
  type MarketplaceAccountRow,
  type StockPushItem,
} from "./queries/marketplaces";
// Phase 14 — reports, discounts, campaigns
export {
  getSalesReport,
  getRepeatCohorts,
  getStockValue,
  reportCsv,
  type ReportRange,
  type ReportKpis,
  type SalesReport,
  type RepeatCohort,
  type StockValue,
  type ReportExport,
} from "./queries/reports";
export { getDiscountSettings, saveDiscountSettings, DiscountError, type DiscountSettings, type CouponUsage } from "./queries/discounts";
export { computeVolumeDiscount, inDiscountWindow, type CheckoutVolumeDiscount, type CheckoutLineForDiscount } from "./types/tenant-checkout";
export {
  CampaignError,
  MAX_CAMPAIGN_RECIPIENTS,
  SEGMENT_KINDS,
  campaignTag,
  cancelCampaign,
  claimCampaignBatches,
  createCampaign,
  describeSegment,
  finishCampaignIfDone,
  getCampaign,
  isCampaignActive,
  listCampaigns,
  normalizeSegment,
  previewSegment,
  queueCampaign,
  recordCampaignSend,
  updateCampaign,
  type CampaignBatch,
  type CampaignRow,
  type CampaignSegment,
  type SegmentKind,
} from "./queries/campaigns";

// Phase 15 — public API, API keys, webhooks
export * from "./types/developer";
export {
  ApiInputError,
  apiCustomersByIds,
  apiGetCustomer,
  apiGetOrder,
  apiGetProduct,
  apiListCustomers,
  apiListInventory,
  apiListOrders,
  apiListProducts,
  apiOrdersByIds,
  apiSetStock,
  apiCreateProduct,
  apiUpdateProduct,
  apiUpdateVariant,
  apiProductsByIds,
  apiVariantsByIds,
  type ApiAddress,
  type ApiCustomer,
  type ApiOrder,
  type ApiOrderFilters,
  type ApiOrderItem,
  type ApiPage,
  type ApiProduct,
  type ApiStockRow,
  type ApiVariant,
} from "./queries/public-api";
export {
  PlatformError,
  authenticateApiToken,
  claimDueDeliveries,
  createApiToken,
  createTestDelivery,
  createWebhookEndpoint,
  deleteWebhookEndpoint,
  fanOutWebhookEvents,
  getWebhookSecretSealed,
  listApiTokens,
  listWebhookDeliveries,
  listWebhookEndpoints,
  pruneWebhookEvents,
  randomSecret,
  recordDeliveryResult,
  redeliverWebhook,
  revokeApiToken,
  setWebhookSecret,
  sha256Hex,
  updateWebhookEndpoint,
  webhookBacklog,
  type ApiPrincipal,
  type ApiTokenRow,
  type DeliveryOutcome,
  type DueDelivery,
  type WebhookDeliveryRow,
  type WebhookEndpointRow,
  type WebhookEnvelope,
} from "./queries/developer";

// Phase 16 — operations, status page, plan billing lifecycle
export {
  alertConditions,
  getOpsSnapshot,
  listAppErrors,
  listCronJobStatus,
  listOpsAlerts,
  markAlertsNotified,
  normalizeErrorMessage,
  pruneCronRuns,
  recordAppError,
  recordCronRuns,
  resolveAppError,
  syncOpsAlerts,
  type AlertCondition,
  type AlertSeverity,
  type AppErrorRow,
  type CronExpectations,
  type CronJobStatus,
  type CronRunInput,
  type OpsAlertRow,
  type OpsSnapshot,
} from "./queries/operations";
export {
  STATUS_COMPONENTS,
  StatusPageError,
  addIncidentUpdate,
  componentForAlert,
  createIncident,
  getIncident,
  getPublicStatus,
  incidentState,
  listIncidents,
  type ComponentState,
  type IncidentView,
  type PublicStatus,
  type StatusComponentId,
} from "./queries/status-page";
export {
  PLAN_GRACE_DAYS,
  dueNoticeKind,
  getBillingOverview,
  getPlanReceipt,
  markNoticeEmailed,
  planStatusOf,
  runPlanLifecycle,
  type BillingNoticeToSend,
  type BillingPaymentRow,
  type NoticeKind,
  type PlanReceipt,
  type PlanState,
  type PlanStatus,
} from "./queries/billing";
export { installConsoleErrorCapture } from "./console-capture";

// Phase 17 — gift cards & store credit, branch stock, POS promos
export {
  GiftCardError,
  adjustGiftCard,
  checkGiftCard,
  checkGiftCardForSlug,
  getGiftCardHistory,
  giftCardSummary,
  issueGiftCard,
  listGiftCards,
  newGiftCardCode,
  normalizeGiftCardCode,
  setGiftCardStatus,
  type GiftCardCheck,
  type GiftCardRow,
  type GiftCardTxnRow,
} from "./queries/gift-cards";
export { computeStorePromotion } from "./types/tenant-checkout";
export { computePosSaleTotals, type PosPromotion } from "./types/pos-tax";
export {
  BranchError,
  MAX_BRANCHES,
  createBranch,
  getBranchStock,
  listBranches,
  resolvePosLocationId,
  setBranchCount,
  transferStock,
  updateBranch,
  type BranchRow,
  type BranchStockRow,
} from "./queries/branches";
export {
  PartnerError,
  createPartnerProfile,
  getPartnerForUser,
  getShopPartner,
  grantPartnerAccess,
  listPartnerShops,
  listPartnersForOps,
  lookupPartnerCode,
  normalizePartnerCode,
  recordPartnerReferral,
  revokePartnerAccess,
  setPartnerStatus,
  touchPartnerOpen,
  updatePartnerProfile,
  verifyPartnerAccess,
  type OpsPartnerRow,
  type PartnerAccessRole,
  type PartnerRow,
  type PartnerShopAccess,
  type PartnerShopRow,
  type PartnerStatus,
  type ShopPartnerView,
} from "./queries/partners";
export { MIGRATION_HEAD } from "./migration-head";
export { getSchemaStatus, isApplied, type SchemaStatus } from "./queries/schema-status";

// Phase 26: AI assistant facts and restock suggestions.
export {
  getRestockSuggestions,
  getAdvisorFacts,
  getReplyFacts,
  restockLine,
  getRevenueForecast,
  forecastRange,
  FORECAST_MIN_HISTORY_DAYS,
  type RevenueForecast,
  type RestockSuggestion,
  type AdvisorFactsRow,
} from "./queries/insights";

// Phase 27: Suki loyalty.
export * from "./types/loyalty";
export {
  LoyaltyError,
  getLoyaltyRules,
  saveLoyaltySettings,
  syncLoyaltyPoints,
  getCustomerLoyalty,
  redeemLoyaltyPoints,
  getLoyaltySummary,
  getOrderLoyalty,
  type CustomerLoyalty,
  type LoyaltySummary,
} from "./queries/loyalty";

// Phase 32: buyer referrals.
export {
  getReferralRules,
  ensureReferralCode,
  attachReferralCode,
  syncReferrals,
  getReferralSummary,
  saveReferralSettings,
  type ReferralSummary,
} from "./queries/referrals";

// Phase 23: verified product reviews.
export {
  REVIEW_WINDOW_DAYS,
  REVIEW_MAX_PHOTOS,
  ReviewError,
  reviewDisplayName,
  reviewEligibility,
  getReviewableItems,
  submitReview,
  listTenantReviews,
  replyToReview,
  setReviewHidden,
  reportReview,
  getTenantReviewStats,
  getProductRatingSummaries,
  listProductReviews,
  listShopReviews,
  getShopReviewHighlights,
  listReportedReviews,
  countOpenReviewReports,
  resolveReviewReport,
  listReviewRequestCandidates,
  type ReviewableItem,
  type ReviewFilter,
  type SellerReviewRow,
  type ReviewStats,
  type RatingSummary,
  type PublicReview,
  type ReportedReviewRow,
} from "./queries/reviews";
