import { DEFAULT_STOREFRONT_SETTINGS } from "./storefront-settings";
import type { StorePatternId } from "@gumakart/storefront-themes";
import { getModelStoreTenant } from "./model-store-tenant";

export interface DemoProduct {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  price: number;
  compareAtPrice?: number;
  image: string;
  category: string;
  categorySlug?: string;
  tags: string[];
  /** Seller identity product — featured first on storefront. */
  isMain?: boolean;
  /** Food unit or service pricing chrome from seller catalog. */
  pricingMeta?: {
    unitType?: "pc" | "box" | "other";
    unitCustom?: string;
    servicePriceStyle?: "base_minimum" | "value_range";
  };
  /** Phase 9: sizes/colours. Only set for products with options. */
  options?: Array<{ name: string; values: string[] }>;
  variants?: Array<{
    id: string;
    title: string;
    options: Record<string, string>;
    price: number;
    compareAtPrice?: number;
    image?: string;
    available: boolean;
  }>;
  /** Phase 23: from published verified reviews only. Absent = no reviews (show nothing). */
  rating?: { average: number; count: number };
  /** Phase 22: false = sold out (all options). Absent = assume available (demo shops). */
  available?: boolean;
  /** Phase 22: on pre-order until this date (YYYY-MM-DD). */
  preorderShipDate?: string;
}

export interface DemoTenant {
  slug: string;
  name: string;
  tagline: string;
  category: string;
  location: string;
  logoEmoji: string;
  logoUrl?: string;
  theme: { primaryColor: string; accentColor: string };
  shopTheme: import("@gumakart/storefront-themes").ResolvedShopTheme;
  shopCategories: Array<{ id: string; name: string; slug: string }>;
  coverUrl?: string;
  codEnabled: boolean;
  storeSettings: import("./storefront-settings").StorefrontStoreSettings;
  products: DemoProduct[];
  subscriptionPlan?: string | null;
  patternId?: StorePatternId;
  seo?: import("@gumakart/db").TenantSeoJson | null;
  /** Phase 23: shop rating from published verified reviews. Absent = none yet. */
  rating?: { average: number; count: number };
  /** Phase 34: set only when the shop has buyer referrals on (amounts from its Suki settings). */
  referral?: { friendReward: number; referrerReward: number; minOrder: number };
}

export const DEMO_TENANT: DemoTenant = {
  slug: "demo",
  name: "Halo Queen Manila",
  tagline: "Premium halo-halo, delivered ice-cold 🍧",
  category: "Food & Beverage",
  location: "Metro Manila",
  logoEmoji: "🍧",
  theme: { primaryColor: "#059669", accentColor: "#f59e0b" },
  shopTheme: {
    templateId: "neon-bazaar",
    tier: "standard",
    label: "Neon Bazaar",
    layout: "bento",
    header: "floating-glass",
    card: "glass-tile",
    hero: "mesh",
    tagline: "Premium halo-halo, delivered ice-cold 🍧",
    promoTitle: "Barkada bucket sale — 4 cups ₱499",
    promoSubtitle: "Order before 8 PM for same-day delivery",
    primaryColor: "#a855f7",
    accentColor: "#22d3ee",
    background: "#020617",
    foreground: "#f8fafc",
    cardBackground: "rgba(15, 23, 42, 0.72)",
    muted: "#94a3b8",
    border: "rgba(148, 163, 184, 0.25)",
    mode: "dark",
    radius: "1rem",
    displayFont: "mono-accent",
    previewGradient: "linear-gradient(135deg, #0f172a 0%, #7c3aed 50%, #22d3ee 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "pro",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    delivery: {
      ...DEFAULT_STOREFRONT_SETTINGS.delivery,
      flatRate: 89,
      freeDeliveryMin: 500,
    },
    whatsapp: {
      enabled: true,
      phone: "+639171234567",
      greeting: "Hi! Order your halo-halo here:",
    },
  },
  shopCategories: [
    { id: "demo-best", name: "Best Sellers", slug: "best-sellers" },
    { id: "demo-specials", name: "Specials", slug: "specials" },
    { id: "demo-classics", name: "Classics", slug: "classics" },
  ],
  products: [
    {
      id: "1",
      slug: "premium-halo-halo",
      title: "Premium Halo-Halo",
      shortDescription: "Loaded with ube, leche flan, and fresh fruits",
      price: 149,
      compareAtPrice: 179,
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80",
      category: "Best Sellers",
      categorySlug: "best-sellers",
      tags: ["bestseller", "summer"],
    },
    {
      id: "2",
      slug: "ube-special",
      title: "Ube Special Halo-Halo",
      shortDescription: "Extra ube halaya for ube lovers",
      price: 169,
      image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
      category: "Specials",
      categorySlug: "specials",
      tags: ["ube"],
    },
    {
      id: "3",
      slug: "family-bucket",
      title: "Family Bucket (4 cups)",
      shortDescription: "Perfect for barkada nights",
      price: 499,
      compareAtPrice: 596,
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600&q=80",
      category: "Bundles",
      categorySlug: "specials",
      tags: ["bundle", "family"],
    },
    {
      id: "4",
      slug: "mais-con-yelo",
      title: "Mais Con Yelo",
      shortDescription: "Classic corn and milk refreshment",
      price: 99,
      image: "https://images.unsplash.com/photo-1625944525533-473f1a9d2c69?w=600&q=80",
      category: "Classics",
      categorySlug: "classics",
      tags: ["classic"],
    },
  ],
};

const BLOOM_DEMO_TENANT: DemoTenant = {
  slug: "bloom-demo",
  name: "Manila Sneaker Co",
  tagline: "Premium sneakers — comfort, design, and performance in every pair.",
  category: "Fashion & Apparel",
  location: "Metro Manila",
  logoEmoji: "👟",
  patternId: "bloom",
  theme: { primaryColor: "#ea580c", accentColor: "#111827" },
  shopTheme: {
    templateId: "bloom",
    tier: "standard",
    label: "Bloom",
    layout: "classic",
    header: "floating-glass",
    card: "grid",
    hero: "gradient",
    tagline: "Premium sneakers — comfort, design, and performance in every pair.",
    promoTitle: "Step Into Style",
    promoSubtitle: "Free delivery on orders ₱1,500+ · COD accepted",
    primaryColor: "#ea580c",
    accentColor: "#111827",
    background: "#ffffff",
    foreground: "#171717",
    cardBackground: "#ffffff",
    muted: "#737373",
    border: "#e5e5e5",
    mode: "light",
    radius: "1.225rem",
    displayFont: "system",
    previewGradient: "linear-gradient(145deg, #fff7ed 0%, #ea580c 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: DEFAULT_STOREFRONT_SETTINGS,
  shopCategories: [{ id: "sneakers", name: "Sneakers", slug: "sneakers" }],
  products: [
    {
      id: "bloom-1",
      slug: "airflex-runner",
      title: "AirFlex Runner",
      shortDescription: "Lightweight running sneakers designed for speed and comfort.",
      price: 4490,
      image:
        "https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: ["bestseller"],
    },
    {
      id: "bloom-2",
      slug: "urban-street-pro",
      title: "Urban Street Pro",
      shortDescription: "Minimalist sneakers for everyday wear with premium leather.",
      price: 4990,
      image:
        "https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: ["new"],
    },
    {
      id: "bloom-3",
      slug: "classic-court-90s",
      title: "Classic Court 90s",
      shortDescription: "Retro-inspired sneakers with a tennis court vibe.",
      price: 3990,
      image:
        "https://images.unsplash.com/photo-1465453869711-7e174808ace9?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: [],
    },
    {
      id: "bloom-4",
      slug: "volt-edge",
      title: "Volt Edge",
      shortDescription: "Performance sneakers with bold details and responsive cushioning.",
      price: 5990,
      image:
        "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: ["featured"],
    },
  ],
};

const SARAB_DEMO_TENANT: DemoTenant = {
  slug: "sarab-demo",
  name: "Sarab Kitchen",
  tagline: "Bold flavors crafted from premium ingredients — burgers, pizza, and more.",
  category: "Food & Beverage",
  location: "Metro Manila",
  logoEmoji: "🍔",
  patternId: "sarab",
  theme: { primaryColor: "#e8281a", accentColor: "#f6a623" },
  shopTheme: {
    templateId: "sarab",
    tier: "standard",
    label: "Sarab",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Bold flavors crafted from premium ingredients — burgers, pizza, and more.",
    promoTitle: "Free Delivery Today!",
    promoSubtitle: "#1 rated fast food in Metro Manila",
    primaryColor: "#e8281a",
    accentColor: "#f6a623",
    background: "#fff8f0",
    foreground: "#1a1a1a",
    cardBackground: "#ffffff",
    muted: "#666666",
    border: "#e5e5e5",
    mode: "light",
    radius: "1.125rem",
    displayFont: "system",
    previewGradient: "linear-gradient(145deg, #fff8f0 0%, #e8281a 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: DEFAULT_STOREFRONT_SETTINGS,
  shopCategories: [
    { id: "burgers", name: "Burgers", slug: "burgers" },
    { id: "pizza", name: "Pizza", slug: "pizza" },
    { id: "chicken", name: "Chicken", slug: "chicken" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  products: [
    {
      id: "sarab-1",
      slug: "classic-smash-burger",
      title: "Classic Smash Burger",
      shortDescription: "Double smashed patties, aged cheddar, caramelized onions, house sauce.",
      price: 289,
      compareAtPrice: 349,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
      category: "Burgers",
      categorySlug: "burgers",
      tags: ["bestseller"],
    },
    {
      id: "sarab-2",
      slug: "margherita-royale",
      title: "Margherita Royale",
      shortDescription: "San Marzano tomatoes, buffalo mozzarella, basil & truffle oil.",
      price: 399,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
      category: "Pizza",
      categorySlug: "pizza",
      tags: ["new"],
    },
    {
      id: "sarab-3",
      slug: "nashville-hot-chicken",
      title: "Nashville Hot Chicken",
      shortDescription: "Extra-crispy fried chicken in fiery Nashville spice blend.",
      price: 259,
      compareAtPrice: 329,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80",
      category: "Chicken",
      categorySlug: "chicken",
      tags: ["bestseller"],
    },
    {
      id: "sarab-4",
      slug: "loaded-fajita-wrap",
      title: "Loaded Fajita Wrap",
      shortDescription: "Grilled chicken, peppers, sour cream & guacamole in a warm tortilla.",
      price: 219,
      image: "https://images.unsplash.com/photo-1626700051175-6818013e5787?w=800&q=80",
      category: "Wraps",
      categorySlug: "wraps",
      tags: [],
    },
    {
      id: "sarab-5",
      slug: "nutella-lava-cake",
      title: "Nutella Lava Cake",
      shortDescription: "Molten chocolate cake with Nutella center and vanilla ice cream.",
      price: 179,
      compareAtPrice: 229,
      image: "https://images.unsplash.com/photo-1624353365286-3f8ed06f7330?w=800&q=80",
      category: "Desserts",
      categorySlug: "desserts",
      tags: ["new"],
    },
    {
      id: "sarab-6",
      slug: "truffle-mushroom-pasta",
      title: "Truffle Mushroom Pasta",
      shortDescription: "Tagliatelle, wild mushrooms, black truffle, parmesan & thyme.",
      price: 349,
      image: "https://images.unsplash.com/photo-1476124369801-6140ca4aa840?w=800&q=80",
      category: "Pasta",
      categorySlug: "pasta",
      tags: [],
    },
  ],
};

const FURNISH_DEMO_TENANT: DemoTenant = {
  slug: "furnish-demo",
  name: "Atelier Home",
  tagline:
    "Modern furniture for living and working — crafted comfort for every room in your home.",
  category: "Furniture & Home",
  location: "Metro Manila",
  logoEmoji: "🛋️",
  patternId: "furnish",
  theme: { primaryColor: "#111100", accentColor: "#d47f31" },
  shopTheme: {
    templateId: "furnish",
    tier: "standard",
    label: "Furnish",
    layout: "editorial",
    header: "minimal",
    card: "grid",
    hero: "photo",
    tagline:
      "Modern furniture for living and working — crafted comfort for every room in your home.",
    promoTitle: "20% Off Comfy Sofas",
    promoSubtitle: "Free delivery on orders ₱5,000+ · COD accepted",
    primaryColor: "#111100",
    accentColor: "#d47f31",
    background: "#ffffff",
    foreground: "#211f1c",
    cardBackground: "#ffffff",
    muted: "#837a6d",
    border: "#ecebe9",
    mode: "light",
    radius: "0",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #f6f5f4 0%, #211f1c 85%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0199",
      greeting: "Hi! I'd like to inquire about furniture:",
    },
  },
  shopCategories: [
    { id: "sofas", name: "Sofas", slug: "sofas" },
    { id: "chairs", name: "Chairs", slug: "chairs" },
    { id: "lighting", name: "Lighting", slug: "lighting" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80",
  products: [
    {
      id: "furnish-1",
      slug: "comfy-sofa-home-office",
      title: "Comfy Sofa Home-Office",
      shortDescription: "Comfortable and stylish sofa for your home office.",
      price: 24990,
      compareAtPrice: 31250,
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      category: "Sofas",
      categorySlug: "sofas",
      tags: ["bestseller"],
    },
    {
      id: "furnish-2",
      slug: "modern-accent-chair",
      title: "Modern Accent Chair",
      shortDescription: "Sculptural lounge chair with walnut legs and linen upholstery.",
      price: 8990,
      compareAtPrice: 11990,
      image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80",
      category: "Chairs",
      categorySlug: "chairs",
      tags: ["new"],
    },
    {
      id: "furnish-3",
      slug: "arc-floor-lamp",
      title: "Arc Floor Lamp",
      shortDescription: "Brushed brass arc lamp with dimmable LED for reading nooks.",
      price: 6490,
      compareAtPrice: 7990,
      image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
      category: "Lighting",
      categorySlug: "lighting",
      tags: [],
    },
    {
      id: "furnish-4",
      slug: "high-back-boss-chair",
      title: "High Back Boss Chair",
      shortDescription: "Ergonomic executive chair with lumbar support and tilt lock.",
      price: 12990,
      compareAtPrice: 15990,
      image: "https://images.unsplash.com/photo-1580480057633-98046edc5dae?w=800&q=80",
      category: "Chairs",
      categorySlug: "chairs",
      tags: ["bestseller"],
    },
    {
      id: "furnish-5",
      slug: "marble-side-table",
      title: "Marble Side Table",
      shortDescription: "Carrara marble top with matte black steel frame.",
      price: 4990,
      compareAtPrice: 5990,
      image: "https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800&q=80",
      category: "Tables",
      categorySlug: "tables",
      tags: [],
    },
    {
      id: "furnish-6",
      slug: "sectional-lounge-set",
      title: "Sectional Lounge Set",
      shortDescription: "Modular sectional with deep cushions and stain-resistant fabric.",
      price: 45990,
      compareAtPrice: 54990,
      image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80",
      category: "Sofas",
      categorySlug: "sofas",
      tags: ["new"],
    },
  ],
};

const ZAY_DEMO_TENANT: DemoTenant = {
  slug: "zay-demo",
  name: "Zay Market",
  tagline: "Quality products for everyday life — watches, shoes, accessories, and more.",
  category: "Retail & General Merchandise",
  location: "Metro Manila",
  logoEmoji: "🛍️",
  patternId: "zay",
  theme: { primaryColor: "#59ab6e", accentColor: "#212934" },
  shopTheme: {
    templateId: "zay",
    tier: "standard",
    label: "Zay Shop",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Quality products for everyday life — watches, shoes, accessories, and more.",
    promoTitle: "Spring Collection Sale",
    promoSubtitle: "Free delivery on orders ₱999+ · COD accepted nationwide",
    primaryColor: "#59ab6e",
    accentColor: "#212934",
    background: "#ffffff",
    foreground: "#212934",
    cardBackground: "#ffffff",
    muted: "#bcbcbc",
    border: "#e9eef5",
    mode: "light",
    radius: "0.375rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #e9eef5 0%, #59ab6e 55%, #212934 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0288",
      greeting: "Hi! I'd like to order from Zay Market:",
    },
  },
  shopCategories: [
    { id: "watches", name: "Watches", slug: "watches" },
    { id: "shoes", name: "Shoes", slug: "shoes" },
    { id: "accessories", name: "Accessories", slug: "accessories" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=900&q=80",
  products: [
    {
      id: "zay-1",
      slug: "classic-leather-watch",
      title: "Classic Leather Watch",
      shortDescription: "Minimalist analog watch with genuine leather strap.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      category: "Watches",
      categorySlug: "watches",
      tags: ["bestseller"],
    },
    {
      id: "zay-2",
      slug: "urban-runner-shoes",
      title: "Urban Runner Shoes",
      shortDescription: "Lightweight sneakers with breathable mesh upper.",
      price: 3290,
      compareAtPrice: 3990,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      category: "Shoes",
      categorySlug: "shoes",
      tags: ["new"],
    },
    {
      id: "zay-3",
      slug: "polaroid-camera-kit",
      title: "Polaroid Camera Kit",
      shortDescription: "Instant camera bundle with film pack and carrying case.",
      price: 4590,
      image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: [],
    },
    {
      id: "zay-4",
      slug: "gym-weight-set",
      title: "Gym Weight Set",
      shortDescription: "Adjustable dumbbell set for home workouts.",
      price: 5990,
      compareAtPrice: 7490,
      image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: ["bestseller"],
    },
    {
      id: "zay-5",
      slug: "canvas-tote-bag",
      title: "Canvas Tote Bag",
      shortDescription: "Durable everyday tote with inner pocket.",
      price: 890,
      image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: [],
    },
    {
      id: "zay-6",
      slug: "sport-sunglasses",
      title: "Sport Sunglasses",
      shortDescription: "UV400 polarized lenses with flexible TR90 frame.",
      price: 1290,
      compareAtPrice: 1590,
      image: "https://images.unsplash.com/photo-1572635196233-14fbfa4036f1?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: ["new"],
    },
  ],
};

const ELECTRO_DEMO_TENANT: DemoTenant = {
  slug: "electro-demo",
  name: "Electro Hub",
  tagline: "Latest gadgets, laptops, phones, and smart devices — official warranty on all items.",
  category: "Electronics",
  location: "Metro Manila",
  logoEmoji: "📱",
  patternId: "electro",
  theme: { primaryColor: "#F28B00", accentColor: "#F92400" },
  shopTheme: {
    templateId: "electro",
    tier: "standard",
    label: "Electro",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Latest gadgets, laptops, phones, and smart devices — official warranty on all items.",
    promoTitle: "Save Up To ₱4,000",
    promoSubtitle: "On selected laptops, desktops & smartphones · Free delivery ₱3,000+",
    primaryColor: "#F28B00",
    accentColor: "#F92400",
    background: "#ffffff",
    foreground: "#484848",
    cardBackground: "#ffffff",
    muted: "#6c757d",
    border: "#e9ecef",
    mode: "light",
    radius: "0.5rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #fff5eb 0%, #F28B00 50%, #F92400 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0311",
      greeting: "Hi! I'd like to inquire about electronics:",
    },
  },
  shopCategories: [
    { id: "phones", name: "Mobiles & Tablets", slug: "phones" },
    { id: "laptops", name: "Laptops & Desktops", slug: "laptops" },
    { id: "accessories", name: "Accessories", slug: "accessories" },
    { id: "smart-tv", name: "Smart TV", slug: "smart-tv" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=900&q=80",
  products: [
    {
      id: "electro-1",
      slug: "iphone-15-pro",
      title: "iPhone 15 Pro 256GB",
      shortDescription: "Titanium design, A17 Pro chip, and pro camera system.",
      price: 64990,
      compareAtPrice: 69990,
      image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
      category: "Mobiles & Tablets",
      categorySlug: "phones",
      tags: ["bestseller"],
    },
    {
      id: "electro-2",
      slug: "macbook-air-m3",
      title: "MacBook Air M3",
      shortDescription: "13-inch, 16GB RAM, 512GB SSD — ultraportable power.",
      price: 79990,
      compareAtPrice: 84990,
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
      category: "Laptops & Desktops",
      categorySlug: "laptops",
      tags: ["new"],
    },
    {
      id: "electro-3",
      slug: "galaxy-watch-ultra",
      title: "Galaxy Watch Ultra",
      shortDescription: "Rugged smartwatch with dual-frequency GPS and titanium case.",
      price: 24990,
      compareAtPrice: 27990,
      image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: ["new"],
    },
    {
      id: "electro-4",
      slug: "sony-wh1000xm5",
      title: "Sony WH-1000XM5",
      shortDescription: "Industry-leading noise cancelling wireless headphones.",
      price: 18990,
      compareAtPrice: 21990,
      image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: ["bestseller"],
    },
    {
      id: "electro-5",
      slug: "samsung-oled-tv-55",
      title: 'Samsung OLED TV 55"',
      shortDescription: "4K OLED smart TV with Neural Quantum Processor.",
      price: 89990,
      compareAtPrice: 99990,
      image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80",
      category: "Smart TV",
      categorySlug: "smart-tv",
      tags: [],
    },
    {
      id: "electro-6",
      slug: "ipad-air-m2",
      title: "iPad Air M2",
      shortDescription: "11-inch Liquid Retina display with Apple Pencil support.",
      price: 42990,
      compareAtPrice: 45990,
      image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80",
      category: "Mobiles & Tablets",
      categorySlug: "phones",
      tags: ["bestseller"],
    },
    {
      id: "electro-7",
      slug: "logitech-mx-master-3s",
      title: "Logitech MX Master 3S",
      shortDescription: "Ergonomic wireless mouse with quiet clicks and MagSpeed scroll.",
      price: 5490,
      image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: [],
    },
    {
      id: "electro-8",
      slug: "asus-rog-laptop",
      title: "ASUS ROG Strix G16",
      shortDescription: "RTX 4060, Intel i7, 16GB RAM — gaming and creator laptop.",
      price: 89990,
      compareAtPrice: 94990,
      image: "https://images.unsplash.com/photo-1603302576837-375698b227cb?w=800&q=80",
      category: "Laptops & Desktops",
      categorySlug: "laptops",
      tags: ["new"],
    },
  ],
};

const KAIRA_DEMO_TENANT: DemoTenant = {
  slug: "kaira-demo",
  name: "Kaira Studio",
  tagline: "Curated fashion for modern living — timeless pieces with an editorial edge.",
  category: "Fashion & Apparel",
  location: "Metro Manila",
  logoEmoji: "👗",
  patternId: "kaira",
  theme: { primaryColor: "#8C907E", accentColor: "#111111" },
  shopTheme: {
    templateId: "kaira",
    tier: "standard",
    label: "Kaira",
    layout: "editorial",
    header: "minimal",
    card: "magazine",
    hero: "photo",
    tagline: "Curated fashion for modern living — timeless pieces with an editorial edge.",
    promoTitle: "Classic Winter Collection",
    promoSubtitle: "Free delivery on orders ₱2,500+ · Easy 30-day returns",
    primaryColor: "#8C907E",
    accentColor: "#111111",
    background: "#ffffff",
    foreground: "#111111",
    cardBackground: "#ffffff",
    muted: "#8f8f8f",
    border: "#F1F1F0",
    mode: "light",
    radius: "0",
    displayFont: "bricolage",
    previewGradient: "linear-gradient(160deg, #F1F1F0 0%, #8C907E 70%, #111111 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0422",
      greeting: "Hi! I'd like to inquire about fashion items:",
    },
  },
  shopCategories: [
    { id: "women", name: "Women", slug: "women" },
    { id: "men", name: "Men", slug: "men" },
    { id: "accessories", name: "Accessories", slug: "accessories" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=900&q=80",
  products: [
    {
      id: "kaira-1",
      slug: "linen-wrap-dress",
      title: "Linen Wrap Dress",
      shortDescription: "Relaxed-fit wrap dress in breathable European linen.",
      price: 3490,
      compareAtPrice: 4290,
      image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80",
      category: "Women",
      categorySlug: "women",
      tags: ["new"],
    },
    {
      id: "kaira-2",
      slug: "oversized-wool-coat",
      title: "Oversized Wool Coat",
      shortDescription: "Double-breasted coat in soft merino wool blend.",
      price: 5990,
      compareAtPrice: 7490,
      image: "https://images.unsplash.com/photo-1539533018447-63fcce267634?w=800&q=80",
      category: "Women",
      categorySlug: "women",
      tags: ["bestseller"],
    },
    {
      id: "kaira-3",
      slug: "structured-blazer",
      title: "Structured Blazer",
      shortDescription: "Tailored blazer with satin lining and notch lapels.",
      price: 4290,
      image: "https://images.unsplash.com/photo-1591369822095-ffd29a94b141?w=800&q=80",
      category: "Men",
      categorySlug: "men",
      tags: ["bestseller"],
    },
    {
      id: "kaira-4",
      slug: "cotton-utility-shirt",
      title: "Cotton Utility Shirt",
      shortDescription: "Garment-dyed shirt with chest pockets and relaxed cut.",
      price: 2190,
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
      category: "Men",
      categorySlug: "men",
      tags: ["new"],
    },
    {
      id: "kaira-5",
      slug: "leather-crossbody",
      title: "Leather Crossbody Bag",
      shortDescription: "Full-grain leather bag with adjustable strap.",
      price: 3890,
      compareAtPrice: 4590,
      image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: ["bestseller"],
    },
    {
      id: "kaira-6",
      slug: "gold-hoop-earrings",
      title: "Gold Hoop Earrings",
      shortDescription: "18K gold-plated hoops with secure clasp closure.",
      price: 1290,
      image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: [],
    },
    {
      id: "kaira-7",
      slug: "wide-leg-trousers",
      title: "Wide Leg Trousers",
      shortDescription: "High-waist trousers in flowing crepe fabric.",
      price: 2790,
      compareAtPrice: 3290,
      image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80",
      category: "Women",
      categorySlug: "women",
      tags: ["new"],
    },
    {
      id: "kaira-8",
      slug: "knit-polo-shirt",
      title: "Knit Polo Shirt",
      shortDescription: "Fine-gauge cotton knit with ribbed collar and cuffs.",
      price: 2490,
      image: "https://images.unsplash.com/photo-1622445275463-ada1584e66f4?w=800&q=80",
      category: "Men",
      categorySlug: "men",
      tags: [],
    },
  ],
};

const FOODMART_DEMO_TENANT: DemoTenant = {
  slug: "foodmart-demo",
  name: "FoodMart Manila",
  tagline: "Fresh groceries, pantry staples, and household essentials — delivered to your door.",
  category: "Grocery & Supermarket",
  location: "Metro Manila",
  logoEmoji: "🛒",
  patternId: "foodmart",
  theme: { primaryColor: "#FFC43F", accentColor: "#6995B1" },
  shopTheme: {
    templateId: "foodmart",
    tier: "standard",
    label: "FoodMart",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Fresh groceries, pantry staples, and household essentials — delivered to your door.",
    promoTitle: "Fresh Smoothie & Summer Juice",
    promoSubtitle: "Free delivery on orders ₱799+ · COD accepted · Same-day in Metro Manila",
    primaryColor: "#FFC43F",
    accentColor: "#6995B1",
    background: "#ffffff",
    foreground: "#212529",
    cardBackground: "#ffffff",
    muted: "#6c757d",
    border: "#eef1f3",
    mode: "light",
    radius: "1rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #FFF9EB 0%, #FFC43F 50%, #6995B1 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0555",
      greeting: "Hi! I'd like to order groceries:",
    },
  },
  shopCategories: [
    { id: "produce", name: "Fruits & Veges", slug: "produce" },
    { id: "bakery", name: "Breads & Sweets", slug: "bakery" },
    { id: "drinks", name: "Drinks", slug: "drinks" },
    { id: "pantry", name: "Pantry", slug: "pantry" },
    { id: "meat", name: "Meat & Poultry", slug: "meat" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=900&q=80",
  products: [
    {
      id: "fm-1",
      slug: "fresh-banana-bunch",
      title: "Fresh Banana Bunch",
      shortDescription: "Locally sourced saba bananas, perfect for snacks and smoothies.",
      price: 89,
      compareAtPrice: 109,
      image: "https://images.unsplash.com/photo-1464965911861-746a04a4b936?w=800&q=80",
      category: "Fruits & Veges",
      categorySlug: "produce",
      tags: ["bestseller"],
    },
    {
      id: "fm-2",
      slug: "organic-tomatoes",
      title: "Organic Tomatoes 1kg",
      shortDescription: "Vine-ripened tomatoes from Benguet farms.",
      price: 129,
      image: "https://images.unsplash.com/photo-1546094097-89a8354a7572?w=800&q=80",
      category: "Fruits & Veges",
      categorySlug: "produce",
      tags: ["new"],
    },
    {
      id: "fm-3",
      slug: "whole-wheat-bread",
      title: "Whole Wheat Bread Loaf",
      shortDescription: "Freshly baked daily, no artificial preservatives.",
      price: 95,
      compareAtPrice: 115,
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
      category: "Breads & Sweets",
      categorySlug: "bakery",
      tags: ["bestseller"],
    },
    {
      id: "fm-4",
      slug: "fresh-milk-1L",
      title: "Fresh Milk 1L",
      shortDescription: "UHT whole milk, rich and creamy.",
      price: 89,
      image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&q=80",
      category: "Drinks",
      categorySlug: "drinks",
      tags: [],
    },
    {
      id: "fm-5",
      slug: "premium-jasmine-rice",
      title: "Premium Jasmine Rice 5kg",
      shortDescription: "Long-grain Thai jasmine rice, fragrant and fluffy.",
      price: 449,
      compareAtPrice: 499,
      image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80",
      category: "Pantry",
      categorySlug: "pantry",
      tags: ["bestseller"],
    },
    {
      id: "fm-6",
      slug: "free-range-eggs",
      title: "Free Range Eggs (12pcs)",
      shortDescription: "Farm-fresh brown eggs from cage-free hens.",
      price: 189,
      image: "https://images.unsplash.com/photo-1582722870445-44dc4157b8a0?w=800&q=80",
      category: "Pantry",
      categorySlug: "pantry",
      tags: ["new"],
    },
    {
      id: "fm-7",
      slug: "chicken-breast-500g",
      title: "Chicken Breast 500g",
      shortDescription: "Trimmed boneless chicken breast, chilled.",
      price: 159,
      compareAtPrice: 189,
      image: "https://images.unsplash.com/photo-1604503468506-4408738831a6?w=800&q=80",
      category: "Meat & Poultry",
      categorySlug: "meat",
      tags: [],
    },
    {
      id: "fm-8",
      slug: "orange-juice-1L",
      title: "100% Orange Juice 1L",
      shortDescription: "No added sugar, cold-pressed orange juice.",
      price: 149,
      compareAtPrice: 179,
      image: "https://images.unsplash.com/photo-1621506289937-a8e4df240312?w=800&q=80",
      category: "Drinks",
      categorySlug: "drinks",
      tags: ["new"],
    },
  ],
};

const STYLISH_DEMO_TENANT: DemoTenant = {
  slug: "stylish-demo",
  name: "Stylish Manila",
  tagline: "Premium footwear and apparel — from everyday sneakers to statement streetwear.",
  category: "Shoes & Footwear",
  location: "Metro Manila",
  logoEmoji: "👟",
  patternId: "stylish",
  theme: { primaryColor: "#ce071e", accentColor: "#111111" },
  shopTheme: {
    templateId: "stylish",
    tier: "standard",
    label: "Stylish",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Premium footwear and apparel — from everyday sneakers to statement streetwear.",
    promoTitle: "Stylish Shoes for Everyone",
    promoSubtitle: "Free shipping on orders ₱2,500+ · Easy 30-day returns",
    primaryColor: "#ce071e",
    accentColor: "#111111",
    background: "#ffffff",
    foreground: "#111111",
    cardBackground: "#ffffff",
    muted: "#8f8f8f",
    border: "#F1F1F0",
    mode: "light",
    radius: "0",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #F1F1F0 0%, #ce071e 55%, #111111 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0666",
      greeting: "Hi! I'd like to inquire about shoes:",
    },
  },
  shopCategories: [
    { id: "men", name: "Men", slug: "men" },
    { id: "women", name: "Women", slug: "women" },
    { id: "sneakers", name: "Sneakers", slug: "sneakers" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=1200&q=80",
  products: [
    {
      id: "stylish-1",
      slug: "air-run-pro",
      title: "Air Run Pro Sneakers",
      shortDescription: "Lightweight mesh upper with responsive foam midsole for daily runs.",
      price: 4990,
      compareAtPrice: 5990,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: ["bestseller"],
    },
    {
      id: "stylish-2",
      slug: "classic-leather-loafers",
      title: "Classic Leather Loafers",
      shortDescription: "Hand-finished leather loafers with cushioned insole.",
      price: 4290,
      image: "https://images.unsplash.com/photo-1533867617851-e774b2f547ec?w=800&q=80",
      category: "Men",
      categorySlug: "men",
      tags: ["bestseller"],
    },
    {
      id: "stylish-3",
      slug: "urban-street-high",
      title: "Urban Street High-Tops",
      shortDescription: "Canvas high-tops with rubber cupsole and padded collar.",
      price: 3490,
      compareAtPrice: 3990,
      image: "https://images.unsplash.com/photo-1606107557195-0fa42b838e10?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: ["new"],
    },
    {
      id: "stylish-4",
      slug: "trail-grip-boots",
      title: "Trail Grip Boots",
      shortDescription: "Water-resistant hiking boots with aggressive tread pattern.",
      price: 5490,
      image: "https://images.unsplash.com/photo-1608256246200-53bd35f2f916?w=800&q=80",
      category: "Men",
      categorySlug: "men",
      tags: ["new"],
    },
    {
      id: "stylish-5",
      slug: "ballet-flat-leather",
      title: "Ballet Flat Leather",
      shortDescription: "Soft leather ballet flats with flexible sole.",
      price: 2790,
      image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
      category: "Women",
      categorySlug: "women",
      tags: ["bestseller"],
    },
    {
      id: "stylish-6",
      slug: "platform-sneaker-white",
      title: "Platform Sneaker White",
      shortDescription: "Chunky platform sole with premium leather upper.",
      price: 3890,
      compareAtPrice: 4590,
      image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
      category: "Women",
      categorySlug: "women",
      tags: ["new"],
    },
    {
      id: "stylish-7",
      slug: "retro-runner-84",
      title: "Retro Runner '84",
      shortDescription: "Vintage-inspired runner with suede overlays and gum sole.",
      price: 4590,
      image: "https://images.unsplash.com/photo-1603487742131-4160ec998306?w=800&q=80",
      category: "Sneakers",
      categorySlug: "sneakers",
      tags: ["bestseller"],
    },
    {
      id: "stylish-8",
      slug: "slide-sandal-comfort",
      title: "Slide Sandal Comfort",
      shortDescription: "Contoured footbed slides with quick-dry strap.",
      price: 1890,
      image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80",
      category: "Women",
      categorySlug: "women",
      tags: [],
    },
  ],
};

const MELLOW_DEMO_TENANT: DemoTenant = {
  slug: "mellow-demo",
  name: "Hotel Mellow",
  tagline: "Your gateway to serenity — boutique comfort in the heart of Metro Manila.",
  category: "Hotels & Resorts",
  location: "Bonifacio Global City, Metro Manila",
  logoEmoji: "🏨",
  patternId: "mellow",
  theme: { primaryColor: "#D16806", accentColor: "#1A1A1A" },
  shopTheme: {
    templateId: "mellow",
    tier: "standard",
    label: "Mellow",
    layout: "hero-stack",
    header: "standard",
    card: "magazine",
    hero: "photo",
    tagline: "Your gateway to serenity — boutique comfort in the heart of Metro Manila.",
    promoTitle: "Hotel Mellow — Your Gateway to Serenity",
    promoSubtitle: "Free breakfast on direct bookings · Flexible check-in · COD accepted",
    primaryColor: "#D16806",
    accentColor: "#1A1A1A",
    background: "#ffffff",
    foreground: "#353535",
    cardBackground: "#F9F6F3",
    muted: "#777F81",
    border: "#EAE5DD",
    mode: "light",
    radius: "1.25rem",
    displayFont: "bricolage",
    previewGradient: "linear-gradient(160deg, #F9F6F3 0%, #D16806 55%, #1A1A1A 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0777",
      greeting: "Hi! I'd like to inquire about room availability:",
    },
  },
  shopCategories: [
    { id: "deluxe", name: "Deluxe", slug: "deluxe" },
    { id: "suite", name: "Suites", slug: "suite" },
    { id: "family", name: "Family", slug: "family" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&q=80",
  products: [
    {
      id: "mellow-1",
      slug: "grand-deluxe-room",
      title: "Grand Deluxe Room",
      shortDescription: "King bed, city view, marble bathroom, and complimentary minibar.",
      price: 8990,
      compareAtPrice: 10990,
      image: "https://images.unsplash.com/photo-1611892440504-42a792e284de?w=800&q=80",
      category: "Deluxe",
      categorySlug: "deluxe",
      tags: ["bestseller"],
    },
    {
      id: "mellow-2",
      slug: "sweet-family-room",
      title: "Sweet Family Room",
      shortDescription: "Two queen beds, sofa nook, and connecting bath — ideal for families.",
      price: 11990,
      image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
      category: "Family",
      categorySlug: "family",
      tags: ["bestseller"],
    },
    {
      id: "mellow-3",
      slug: "perfect-double-room",
      title: "Perfect Double Room",
      shortDescription: "Cozy double room with garden view and rain shower.",
      price: 7490,
      compareAtPrice: 8490,
      image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
      category: "Deluxe",
      categorySlug: "deluxe",
      tags: ["new"],
    },
    {
      id: "mellow-4",
      slug: "executive-suite",
      title: "Executive Suite",
      shortDescription: "Separate living area, work desk, and premium amenities.",
      price: 14990,
      image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80",
      category: "Suites",
      categorySlug: "suite",
      tags: ["new"],
    },
    {
      id: "mellow-5",
      slug: "garden-villa",
      title: "Garden Villa",
      shortDescription: "Private terrace, outdoor seating, and butler service on request.",
      price: 18990,
      compareAtPrice: 21990,
      image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
      category: "Suites",
      categorySlug: "suite",
      tags: ["bestseller"],
    },
    {
      id: "mellow-6",
      slug: "studio-loft",
      title: "Studio Loft",
      shortDescription: "Open-plan loft with kitchenette — perfect for extended stays.",
      price: 9990,
      image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80",
      category: "Deluxe",
      categorySlug: "deluxe",
      tags: [],
    },
  ],
};

const ORGANIC_DEMO_TENANT: DemoTenant = {
  slug: "organic-demo",
  name: "GreenHarvest Farm",
  tagline: "Farm-fresh organic vegetables, fruits, and pantry staples — straight from local partner farms.",
  category: "Organic & Farm Produce",
  location: "Laguna & Cavite",
  logoEmoji: "🌿",
  patternId: "organic",
  theme: { primaryColor: "#6BB252", accentColor: "#364127" },
  shopTheme: {
    templateId: "organic",
    tier: "standard",
    label: "Organic",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Farm-fresh organic vegetables, fruits, and pantry staples — straight from local partner farms.",
    promoTitle: "Organic Foods at Your Doorstep",
    promoSubtitle: "Free delivery on orders ₱999+ · Harvested within 24 hours · COD accepted",
    primaryColor: "#6BB252",
    accentColor: "#364127",
    background: "#ffffff",
    foreground: "#333333",
    cardBackground: "#ffffff",
    muted: "#747474",
    border: "#F7F7F7",
    mode: "light",
    radius: "0.75rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #FFF9EB 0%, #6BB252 55%, #364127 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0888",
      greeting: "Hi! I'd like to order fresh produce:",
    },
  },
  shopCategories: [
    { id: "vegetables", name: "Vegetables", slug: "vegetables" },
    { id: "fruits", name: "Fruits", slug: "fruits" },
    { id: "herbs", name: "Herbs & Greens", slug: "herbs" },
    { id: "pantry", name: "Pantry", slug: "pantry" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&q=80",
  products: [
    {
      id: "organic-1",
      slug: "organic-kale-bunch",
      title: "Organic Kale Bunch",
      shortDescription: "Crisp curly kale, pesticide-free from partner farms in Laguna.",
      price: 189,
      compareAtPrice: 229,
      image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["bestseller"],
    },
    {
      id: "organic-2",
      slug: "heirloom-tomatoes",
      title: "Heirloom Tomatoes (500g)",
      shortDescription: "Mixed color heirloom tomatoes, vine-ripened and hand-picked.",
      price: 249,
      image: "https://images.unsplash.com/photo-1546094096-0df4faaa2f59?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["bestseller"],
    },
    {
      id: "organic-3",
      slug: "fresh-strawberries",
      title: "Fresh Strawberries (250g)",
      shortDescription: "Sweet Benguet strawberries packed same-day.",
      price: 299,
      compareAtPrice: 349,
      image: "https://images.unsplash.com/photo-1464965911861-746a04a4b936?w=800&q=80",
      category: "Fruits",
      categorySlug: "fruits",
      tags: ["new"],
    },
    {
      id: "organic-4",
      slug: "organic-carrots",
      title: "Organic Carrots (1kg)",
      shortDescription: "Sweet crunchy carrots, ideal for juicing and cooking.",
      price: 159,
      image: "https://images.unsplash.com/photo-1598170845058-32b9d6a594c0?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["bestseller"],
    },
    {
      id: "organic-5",
      slug: "basil-herb-pack",
      title: "Basil Herb Pack",
      shortDescription: "Fresh basil leaves in compostable packaging.",
      price: 89,
      image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=800&q=80",
      category: "Herbs & Greens",
      categorySlug: "herbs",
      tags: ["new"],
    },
    {
      id: "organic-6",
      slug: "free-range-eggs",
      title: "Free-Range Eggs (12 pcs)",
      shortDescription: "Pasture-raised eggs from smallholder farms.",
      price: 219,
      compareAtPrice: 249,
      image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&q=80",
      category: "Pantry",
      categorySlug: "pantry",
      tags: ["bestseller"],
    },
    {
      id: "organic-7",
      slug: "organic-honey-jar",
      title: "Raw Organic Honey (350g)",
      shortDescription: "Unfiltered wildflower honey from Batangas apiaries.",
      price: 389,
      image: "https://images.unsplash.com/photo-1587049352846-99a5263a65c9?w=800&q=80",
      category: "Pantry",
      categorySlug: "pantry",
      tags: [],
    },
    {
      id: "organic-8",
      slug: "mixed-salad-greens",
      title: "Mixed Salad Greens (200g)",
      shortDescription: "Pre-washed romaine, arugula, and baby spinach blend.",
      price: 199,
      compareAtPrice: 239,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      category: "Herbs & Greens",
      categorySlug: "herbs",
      tags: ["new"],
    },
  ],
};

const WAGGY_DEMO_TENANT: DemoTenant = {
  slug: "waggy-demo",
  name: "Waggy Pet Shop",
  tagline: "Everything your furry, feathered, and finned friends need — food, toys, clothing, and care.",
  category: "Pet Supplies & Lovers",
  location: "Quezon City, Metro Manila",
  logoEmoji: "🐾",
  patternId: "waggy",
  theme: { primaryColor: "#DEAD6F", accentColor: "#333333" },
  shopTheme: {
    templateId: "waggy",
    tier: "standard",
    label: "Waggy",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Everything your furry, feathered, and finned friends need — food, toys, clothing, and care.",
    promoTitle: "Best destination for your pets",
    promoSubtitle: "Free delivery on orders ₱999+ · Vet-approved brands · Same-day pickup available",
    primaryColor: "#DEAD6F",
    accentColor: "#333333",
    background: "#ffffff",
    foreground: "#333333",
    cardBackground: "#F9F3EC",
    muted: "#747474",
    border: "#eeeeee",
    mode: "light",
    radius: "0.75rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #F9F3EC 0%, #DEAD6F 55%, #333333 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0777",
      greeting: "Hi! I'd like to order pet supplies:",
    },
  },
  shopCategories: [
    { id: "food", name: "Pet Food", slug: "food" },
    { id: "dog", name: "Dog Shop", slug: "dog" },
    { id: "cat", name: "Cat Shop", slug: "cat" },
    { id: "bird", name: "Bird Shop", slug: "bird" },
    { id: "fish", name: "Fish Shop", slug: "fish" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=1600&q=80",
  products: [
    {
      id: "waggy-1",
      slug: "premium-dog-kibble",
      title: "Premium Dog Kibble (5kg)",
      shortDescription: "High-protein chicken & rice formula for adult dogs.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1589924691995-400dc963257a?w=800&q=80",
      category: "Pet Food",
      categorySlug: "food",
      tags: ["bestseller"],
    },
    {
      id: "waggy-2",
      slug: "salmon-cat-treats",
      title: "Salmon Cat Treats (120g)",
      shortDescription: "Freeze-dried salmon bites — no fillers, all natural.",
      price: 390,
      image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&q=80",
      category: "Pet Food",
      categorySlug: "food",
      tags: ["bestseller"],
    },
    {
      id: "waggy-3",
      slug: "cozy-dog-hoodie",
      title: "Cozy Dog Hoodie — Gray",
      shortDescription: "Soft fleece hoodie with leash hole, sizes S–XL.",
      price: 890,
      compareAtPrice: 1090,
      image: "https://images.unsplash.com/photo-1591946616308-6e9c977f0a0f?w=800&q=80",
      category: "Dog Shop",
      categorySlug: "dog",
      tags: ["new"],
    },
    {
      id: "waggy-4",
      slug: "reflective-dog-collar",
      title: "Reflective Dog Collar",
      shortDescription: "Adjustable nylon collar with night-safe reflective strip.",
      price: 490,
      image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80",
      category: "Dog Shop",
      categorySlug: "dog",
      tags: ["bestseller"],
    },
    {
      id: "waggy-5",
      slug: "cat-scratching-post",
      title: "Cat Scratching Post Tower",
      shortDescription: "Sisal-wrapped post with plush perch and dangling toy.",
      price: 1890,
      compareAtPrice: 2290,
      image: "https://images.unsplash.com/photo-1513244897147-a852fd314c34?w=800&q=80",
      category: "Cat Shop",
      categorySlug: "cat",
      tags: ["bestseller"],
    },
    {
      id: "waggy-6",
      slug: "bird-seed-mix",
      title: "Premium Bird Seed Mix (1kg)",
      shortDescription: "Blend of millet, sunflower, and fortified pellets.",
      price: 290,
      image: "https://images.unsplash.com/photo-1552728086-57bdde30beb3?w=800&q=80",
      category: "Bird Shop",
      categorySlug: "bird",
      tags: [],
    },
    {
      id: "waggy-7",
      slug: "aquarium-flake-food",
      title: "Aquarium Flake Food (100g)",
      shortDescription: "Color-enhancing tropical fish flakes with vitamins.",
      price: 190,
      image: "https://images.unsplash.com/photo-1522069169874-b58ac69124ae?w=800&q=80",
      category: "Fish Shop",
      categorySlug: "fish",
      tags: ["new"],
    },
    {
      id: "waggy-8",
      slug: "pet-leash-set",
      title: "Matching Leash & Harness Set",
      shortDescription: "Padded harness with quick-release buckle and 1.2m leash.",
      price: 1290,
      compareAtPrice: 1590,
      image: "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=80",
      category: "Dog Shop",
      categorySlug: "dog",
      tags: ["new"],
    },
  ],
};

const FRUITABLES_DEMO_TENANT: DemoTenant = {
  slug: "fruitables-demo",
  name: "Fruitables Market",
  tagline: "Farm-fresh fruits and vegetables delivered daily — colorful, organic, and always in season.",
  category: "Organic & Farm Produce",
  location: "Makati & BGC",
  logoEmoji: "🍎",
  patternId: "fruitables",
  theme: { primaryColor: "#81C408", accentColor: "#FFB524" },
  shopTheme: {
    templateId: "fruitables",
    tier: "standard",
    label: "Fruitables",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Farm-fresh fruits and vegetables delivered daily — colorful, organic, and always in season.",
    promoTitle: "Fresh Exotic Fruits in Our Store",
    promoSubtitle: "Free delivery on orders ₱999+ · Harvested same-day · COD accepted",
    primaryColor: "#81C408",
    accentColor: "#FFB524",
    background: "#ffffff",
    foreground: "#45595B",
    cardBackground: "#F4F6F8",
    muted: "#6c757d",
    border: "#FFB524",
    mode: "light",
    radius: "0.75rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #F4F6F8 0%, #81C408 50%, #FFB524 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0999",
      greeting: "Hi! I'd like to order fresh fruits and vegetables:",
    },
  },
  shopCategories: [
    { id: "fruits", name: "Fruits", slug: "fruits" },
    { id: "vegetables", name: "Vegetables", slug: "vegetables" },
    { id: "herbs", name: "Herbs", slug: "herbs" },
    { id: "pantry", name: "Pantry", slug: "pantry" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&q=80",
  products: [
    {
      id: "fruitables-1",
      slug: "honeycrisp-apples",
      title: "Honeycrisp Apples (1kg)",
      shortDescription: "Crisp and sweet apples perfect for snacking or baking.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800&q=80",
      category: "Fruits",
      categorySlug: "fruits",
      tags: ["bestseller"],
    },
    {
      id: "fruitables-2",
      slug: "fresh-strawberries-box",
      title: "Fresh Strawberries (500g)",
      shortDescription: "Sweet Benguet strawberries packed same-day.",
      price: 3990,
      image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&q=80",
      category: "Fruits",
      categorySlug: "fruits",
      tags: ["new"],
    },
    {
      id: "fruitables-3",
      slug: "organic-carrots-bunch",
      title: "Organic Carrots (1kg)",
      shortDescription: "Sweet crunchy carrots, ideal for juicing and cooking.",
      price: 1590,
      image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["bestseller"],
    },
    {
      id: "fruitables-4",
      slug: "heirloom-tomatoes",
      title: "Heirloom Tomatoes (500g)",
      shortDescription: "Mixed color heirloom tomatoes, vine-ripened and hand-picked.",
      price: 2490,
      compareAtPrice: 2890,
      image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["bestseller"],
    },
    {
      id: "fruitables-5",
      slug: "bell-pepper-trio",
      title: "Bell Pepper Trio (3 pcs)",
      shortDescription: "Red, yellow, and green peppers — crisp and colorful.",
      price: 1890,
      image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["new"],
    },
    {
      id: "fruitables-6",
      slug: "ripe-mangoes",
      title: "Ripe Carabao Mangoes (1kg)",
      shortDescription: "Golden Philippine mangoes at peak sweetness.",
      price: 2990,
      compareAtPrice: 3490,
      image: "https://images.unsplash.com/photo-1518843875459-f738682238a6?w=800&q=80",
      category: "Fruits",
      categorySlug: "fruits",
      tags: ["bestseller"],
    },
    {
      id: "fruitables-7",
      slug: "basil-herb-pack",
      title: "Basil Herb Pack",
      shortDescription: "Fresh basil leaves in compostable packaging.",
      price: 890,
      image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=800&q=80",
      category: "Herbs",
      categorySlug: "herbs",
      tags: ["new"],
    },
    {
      id: "fruitables-8",
      slug: "mixed-salad-greens",
      title: "Mixed Salad Greens (200g)",
      shortDescription: "Pre-washed romaine, arugula, and baby spinach blend.",
      price: 1990,
      compareAtPrice: 2390,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
      category: "Vegetables",
      categorySlug: "vegetables",
      tags: ["new"],
    },
  ],
};

const MINISTORE_DEMO_TENANT: DemoTenant = {
  slug: "ministore-demo",
  name: "MiniStore Tech",
  tagline: "Premium gadgets, phones, and smart wearables — minimal design, maximum performance.",
  category: "Electronics",
  location: "BGC & Ortigas",
  logoEmoji: "📱",
  patternId: "ministore",
  theme: { primaryColor: "#72AEC8", accentColor: "#212529" },
  shopTheme: {
    templateId: "ministore",
    tier: "standard",
    label: "MiniStore",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Premium gadgets, phones, and smart wearables — minimal design, maximum performance.",
    promoTitle: "New Year Tech Sale",
    promoSubtitle: "10% off select phones & watches · Free delivery ₱3,000+ · Official warranty",
    primaryColor: "#72AEC8",
    accentColor: "#212529",
    background: "#ffffff",
    foreground: "#212529",
    cardBackground: "#F3F3F3",
    muted: "#AEAEAE",
    border: "#D8D8D8",
    mode: "light",
    radius: "0",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #EDF1F3 0%, #72AEC8 55%, #212529 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0444",
      greeting: "Hi! I'd like to inquire about gadgets:",
    },
  },
  shopCategories: [
    { id: "phones", name: "Mobile Phones", slug: "phones" },
    { id: "watches", name: "Smart Watches", slug: "watches" },
    { id: "audio", name: "Headphones", slug: "audio" },
    { id: "accessories", name: "Accessories", slug: "accessories" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1600&q=80",
  products: [
    {
      id: "ministore-1",
      slug: "iphone-16-pro",
      title: "iPhone 16 Pro",
      shortDescription: "Titanium frame, A18 Pro chip, and advanced camera system.",
      price: 74990,
      compareAtPrice: 79990,
      image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
      category: "Mobile Phones",
      categorySlug: "phones",
      tags: ["bestseller"],
    },
    {
      id: "ministore-2",
      slug: "galaxy-s25-ultra",
      title: "Galaxy S25 Ultra",
      shortDescription: "200MP camera, S Pen, and Galaxy AI features built in.",
      price: 69990,
      compareAtPrice: 74990,
      image: "https://images.unsplash.com/photo-1610945414895-ec8e0e4e2f1e?w=800&q=80",
      category: "Mobile Phones",
      categorySlug: "phones",
      tags: ["new"],
    },
    {
      id: "ministore-3",
      slug: "pixel-9-pro",
      title: "Google Pixel 9 Pro",
      shortDescription: "Best-in-class computational photography and pure Android.",
      price: 54990,
      image: "https://images.unsplash.com/photo-1598327275664-5b737f3127f2?w=800&q=80",
      category: "Mobile Phones",
      categorySlug: "phones",
      tags: ["bestseller"],
    },
    {
      id: "ministore-4",
      slug: "apple-watch-ultra-2",
      title: "Apple Watch Ultra 2",
      shortDescription: "Rugged titanium case with precision dual-frequency GPS.",
      price: 42990,
      compareAtPrice: 45990,
      image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80",
      category: "Smart Watches",
      categorySlug: "watches",
      tags: ["bestseller"],
    },
    {
      id: "ministore-5",
      slug: "galaxy-watch-7",
      title: "Galaxy Watch 7",
      shortDescription: "Advanced health tracking with sleek rotating bezel design.",
      price: 19990,
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      category: "Smart Watches",
      categorySlug: "watches",
      tags: ["new"],
    },
    {
      id: "ministore-6",
      slug: "fitbit-sense-2",
      title: "Fitbit Sense 2",
      shortDescription: "Stress management, ECG app, and 6-day battery life.",
      price: 14990,
      compareAtPrice: 17990,
      image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80",
      category: "Smart Watches",
      categorySlug: "watches",
      tags: [],
    },
    {
      id: "ministore-7",
      slug: "airpods-pro-2",
      title: "AirPods Pro (2nd Gen)",
      shortDescription: "Active noise cancellation with adaptive transparency mode.",
      price: 12990,
      image: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&q=80",
      category: "Headphones",
      categorySlug: "audio",
      tags: ["bestseller"],
    },
    {
      id: "ministore-8",
      slug: "macbook-air-m3",
      title: "MacBook Air M3",
      shortDescription: "13-inch ultraportable with 18-hour battery and fanless design.",
      price: 79990,
      compareAtPrice: 84990,
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
      category: "Laptops",
      categorySlug: "laptops",
      tags: ["new"],
    },
  ],
};

const AIRCON_DEMO_TENANT: DemoTenant = {
  slug: "aircon-demo",
  name: "CoolAir Metro",
  tagline: "Professional AC installation, repair, and maintenance — keeping Metro Manila cool year-round.",
  category: "HVAC & Air Conditioning",
  location: "Metro Manila",
  logoEmoji: "❄️",
  patternId: "aircon",
  theme: { primaryColor: "#FF800F", accentColor: "#0D1B2A" },
  shopTheme: {
    templateId: "aircon",
    tier: "standard",
    label: "AirCon",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Professional AC installation, repair, and maintenance — keeping Metro Manila cool year-round.",
    promoTitle: "Free AC Health Check This Month",
    promoSubtitle: "Same-day service in Metro Manila · Licensed technicians · COD accepted",
    primaryColor: "#FF800F",
    accentColor: "#0D1B2A",
    background: "#ffffff",
    foreground: "#0D1B2A",
    cardBackground: "#F8F9FA",
    muted: "#6c757d",
    border: "#E9ECEF",
    mode: "light",
    radius: "0.5rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #0D1B2A 0%, #FF800F 55%, #ffffff 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0101",
      greeting: "Hi! I'd like to book an AC service:",
    },
  },
  shopCategories: [
    { id: "services", name: "Services", slug: "services" },
    { id: "installation", name: "Installation", slug: "installation" },
    { id: "maintenance", name: "Maintenance", slug: "maintenance" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1631540570607-8f14fc235eba?w=1600&q=80",
  products: [
    {
      id: "aircon-1",
      slug: "ac-deep-cleaning",
      title: "AC Deep Cleaning Package",
      shortDescription: "Full coil wash, filter replacement, and drain flush for split-type units.",
      price: 1490,
      compareAtPrice: 1890,
      image: "https://images.unsplash.com/photo-1585771724684-b382ce228a84?w=800&q=80",
      category: "Services",
      categorySlug: "services",
      tags: ["bestseller"],
    },
    {
      id: "aircon-2",
      slug: "split-ac-install-1-5hp",
      title: "Split AC Installation (1.5HP)",
      shortDescription: "Includes unit mounting, copper piping up to 3m, and vacuum test.",
      price: 4990,
      image: "https://images.unsplash.com/photo-1631540570607-8f14fc235eba?w=800&q=80",
      category: "Installation",
      categorySlug: "installation",
      tags: ["bestseller"],
    },
    {
      id: "aircon-3",
      slug: "compressor-repair",
      title: "AC Compressor Repair",
      shortDescription: "Diagnosis, parts sourcing, and labor for faulty compressors.",
      price: 3490,
      compareAtPrice: 4290,
      image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80",
      category: "Services",
      categorySlug: "services",
      tags: ["new"],
    },
    {
      id: "aircon-4",
      slug: "annual-maintenance-plan",
      title: "Annual Maintenance Plan",
      shortDescription: "Four scheduled visits per year — cleaning, checks, and priority booking.",
      price: 3990,
      image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80",
      category: "Maintenance",
      categorySlug: "maintenance",
      tags: ["bestseller"],
    },
    {
      id: "aircon-5",
      slug: "refrigerant-refill",
      title: "Refrigerant Refill Service",
      shortDescription: "Leak check and R32/R410A top-up for undercharged split units.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80",
      category: "Services",
      categorySlug: "services",
      tags: [],
    },
    {
      id: "aircon-6",
      slug: "ductless-tune-up",
      title: "Ductless AC Tune-Up",
      shortDescription: "Performance tune, thermostat calibration, and airflow optimization.",
      price: 1290,
      image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
      category: "Maintenance",
      categorySlug: "maintenance",
      tags: ["new"],
    },
  ],
};

const CARSERV_DEMO_TENANT: DemoTenant = {
  slug: "carserv-demo",
  name: "Metro Auto Care",
  tagline: "Trusted auto repair, maintenance, and genuine parts — keeping your ride road-ready.",
  category: "Auto Shop & Services",
  location: "Metro Manila",
  logoEmoji: "🔧",
  patternId: "carserv",
  theme: { primaryColor: "#D81324", accentColor: "#1B1B1B" },
  shopTheme: {
    templateId: "carserv",
    tier: "standard",
    label: "CarServ",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Trusted auto repair, maintenance, and genuine parts — keeping your ride road-ready.",
    promoTitle: "Free 21-Point Inspection",
    promoSubtitle: "Book online · Same-day slots available · COD accepted",
    primaryColor: "#D81324",
    accentColor: "#1B1B1B",
    background: "#ffffff",
    foreground: "#1B1B1B",
    cardBackground: "#F5F5F5",
    muted: "#6c757d",
    border: "#DEE2E6",
    mode: "light",
    radius: "0.35rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #1B1B1B 0%, #D81324 55%, #ffffff 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0202",
      greeting: "Hi! I'd like to book an auto service:",
    },
  },
  shopCategories: [
    { id: "services", name: "Services", slug: "services" },
    { id: "parts", name: "Parts", slug: "parts" },
    { id: "packages", name: "Packages", slug: "packages" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1600&q=80",
  products: [
    {
      id: "carserv-1",
      slug: "full-synthetic-oil-change",
      title: "Full Synthetic Oil Change",
      shortDescription: "Premium synthetic oil, new filter, and multi-point inspection.",
      price: 1890,
      compareAtPrice: 2290,
      image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80",
      category: "Services",
      categorySlug: "services",
      tags: ["bestseller"],
    },
    {
      id: "carserv-2",
      slug: "brake-pad-replacement",
      title: "Brake Pad Replacement",
      shortDescription: "Front or rear pad swap with rotor inspection and bedding.",
      price: 2490,
      image: "https://images.unsplash.com/photo-1619642751034-765cb88327e8?w=800&q=80",
      category: "Services",
      categorySlug: "services",
      tags: ["bestseller"],
    },
    {
      id: "carserv-3",
      slug: "air-filter-replacement",
      title: "Air Filter Replacement",
      shortDescription: "OEM-spec engine and cabin air filters installed.",
      price: 690,
      compareAtPrice: 890,
      image: "https://images.unsplash.com/photo-1625047509168-bd039fdfcb64?w=800&q=80",
      category: "Parts",
      categorySlug: "parts",
      tags: ["new"],
    },
    {
      id: "carserv-4",
      slug: "tire-rotation-balance",
      title: "Tire Rotation & Balance",
      shortDescription: "Four-wheel rotation with computerized balancing.",
      price: 990,
      image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80",
      category: "Services",
      categorySlug: "services",
      tags: [],
    },
    {
      id: "carserv-5",
      slug: "battery-replacement",
      title: "Battery Replacement",
      shortDescription: "New maintenance-free battery with terminal cleaning.",
      price: 4490,
      compareAtPrice: 4990,
      image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80",
      category: "Parts",
      categorySlug: "parts",
      tags: ["bestseller"],
    },
    {
      id: "carserv-6",
      slug: "transmission-fluid-service",
      title: "Transmission Fluid Service",
      shortDescription: "Drain and refill with manufacturer-recommended ATF.",
      price: 1790,
      image: "https://images.unsplash.com/photo-1625047509248-ec889cbff17f?w=800&q=80",
      category: "Packages",
      categorySlug: "packages",
      tags: ["new"],
    },
  ],
};

const MOTTO_DEMO_TENANT: DemoTenant = {
  slug: "motto-demo",
  name: "Motto Gear PH",
  tagline: "Premium motorcycle helmets, riding gear, and accessories — built for Philippine roads.",
  category: "Auto Shop & Services",
  location: "Metro Manila",
  logoEmoji: "🏍️",
  patternId: "motto",
  theme: { primaryColor: "#E10600", accentColor: "#000000" },
  shopTheme: {
    templateId: "motto",
    tier: "standard",
    label: "Motto Moto",
    layout: "classic",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Premium motorcycle helmets, riding gear, and accessories — built for Philippine roads.",
    promoTitle: "Ride Safe Sale — Up to 20% Off",
    promoSubtitle: "Free delivery ₱2,500+ · DOT-approved helmets · COD accepted",
    primaryColor: "#E10600",
    accentColor: "#000000",
    background: "#ffffff",
    foreground: "#000000",
    cardBackground: "#F9F9F9",
    muted: "#6c757d",
    border: "#E5E5E5",
    mode: "light",
    radius: "0",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #000000 0%, #E10600 55%, #ffffff 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0303",
      greeting: "Hi! I'd like to order moto gear:",
    },
  },
  shopCategories: [
    { id: "helmets", name: "Helmets", slug: "helmets" },
    { id: "apparel", name: "Apparel", slug: "apparel" },
    { id: "accessories", name: "Accessories", slug: "accessories" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80",
  products: [
    {
      id: "motto-1",
      slug: "full-face-racing-helmet",
      title: "Full-Face Racing Helmet",
      shortDescription: "DOT-approved shell with anti-fog visor and quick-release buckle.",
      price: 4990,
      compareAtPrice: 5990,
      image: "https://images.unsplash.com/photo-1568774873960-0e29ddd66b08?w=800&q=80",
      category: "Helmets",
      categorySlug: "helmets",
      tags: ["bestseller"],
    },
    {
      id: "motto-2",
      slug: "mesh-riding-jacket",
      title: "Mesh Riding Jacket",
      shortDescription: "CE-rated armor, vented panels, and reflective piping.",
      price: 3490,
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
      category: "Apparel",
      categorySlug: "apparel",
      tags: ["bestseller"],
    },
    {
      id: "motto-3",
      slug: "reinforced-riding-gloves",
      title: "Reinforced Riding Gloves",
      shortDescription: "Leather palm, knuckle guards, and touchscreen fingertips.",
      price: 1290,
      compareAtPrice: 1590,
      image: "https://images.unsplash.com/photo-1558980666-fac64ea8c1d0?w=800&q=80",
      category: "Apparel",
      categorySlug: "apparel",
      tags: ["new"],
    },
    {
      id: "motto-4",
      slug: "armored-riding-pants",
      title: "Armored Riding Pants",
      shortDescription: "Abrasion-resistant textile with removable hip and knee pads.",
      price: 2790,
      image: "https://images.unsplash.com/photo-1609630875171-b1327697c1e0?w=800&q=80",
      category: "Apparel",
      categorySlug: "apparel",
      tags: ["new"],
    },
    {
      id: "motto-5",
      slug: "uv-visor-shield",
      title: "UV Visor Shield",
      shortDescription: "Pinlock-ready smoked visor compatible with major helmet brands.",
      price: 890,
      image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: [],
    },
    {
      id: "motto-6",
      slug: "waterproof-saddle-bag",
      title: "Waterproof Saddle Bag",
      shortDescription: "15L roll-top bag with quick-mount straps and rain cover.",
      price: 2190,
      compareAtPrice: 2590,
      image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
      category: "Accessories",
      categorySlug: "accessories",
      tags: ["bestseller"],
    },
  ],
};

const STUDIO_DEMO_TENANT: DemoTenant = {
  slug: "studio-demo",
  name: "Studio North",
  tagline: "Portrait sessions, event coverage, and premium print & signage — creative work that lasts.",
  category: "Photography & Creative",
  location: "Quezon City, Metro Manila",
  logoEmoji: "📷",
  patternId: "studio",
  theme: { primaryColor: "#1d1d1d", accentColor: "#838383" },
  shopTheme: {
    templateId: "studio",
    tier: "standard",
    label: "Studio",
    layout: "editorial",
    header: "minimal",
    card: "magazine",
    hero: "photo",
    tagline: "Portrait sessions, event coverage, and premium print & signage — creative work that lasts.",
    promoTitle: "Spring Portrait Mini Sessions",
    promoSubtitle: "Book online · Same-week slots · Print-ready files included",
    primaryColor: "#1d1d1d",
    accentColor: "#838383",
    background: "#ffffff",
    foreground: "#1d1d1d",
    cardBackground: "#f6f6f6",
    muted: "#838383",
    border: "#dcdcdc",
    mode: "light",
    radius: "0",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #1d1d1d 0%, #838383 55%, #f6f6f6 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0404",
      greeting: "Hi! I'd like to book a photo session:",
    },
  },
  shopCategories: [
    { id: "sessions", name: "Sessions", slug: "sessions" },
    { id: "prints", name: "Prints", slug: "prints" },
    { id: "signage", name: "Signage", slug: "signage" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1600&q=80",
  products: [
    {
      id: "studio-1",
      slug: "portrait-session-package",
      title: "Portrait Session Package",
      shortDescription: "1-hour studio session with 15 edited digital files.",
      price: 4990,
      compareAtPrice: 5990,
      image: "https://images.unsplash.com/photo-1542038784455-ffefcd2464d?w=800&q=80",
      category: "Sessions",
      categorySlug: "sessions",
      tags: ["bestseller"],
    },
    {
      id: "studio-2",
      slug: "wedding-day-coverage",
      title: "Wedding Day Coverage",
      shortDescription: "8-hour coverage with highlight reel and online gallery.",
      price: 49990,
      image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
      category: "Sessions",
      categorySlug: "sessions",
      tags: ["bestseller"],
    },
    {
      id: "studio-3",
      slug: "business-headshot-mini",
      title: "Business Headshot Mini",
      shortDescription: "30-minute session with 5 retouched portraits for LinkedIn.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80",
      category: "Sessions",
      categorySlug: "sessions",
      tags: ["new"],
    },
    {
      id: "studio-4",
      slug: "canvas-print-16x20",
      title: 'Canvas Print 16×20"',
      shortDescription: "Gallery-wrapped canvas with UV-resistant inks.",
      price: 1890,
      image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80",
      category: "Prints",
      categorySlug: "prints",
      tags: ["print"],
    },
    {
      id: "studio-5",
      slug: "vinyl-banner-3x6",
      title: 'Vinyl Banner 3×6 ft',
      shortDescription: "Weather-resistant full-color banner with grommets.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80",
      category: "Signage",
      categorySlug: "signage",
      tags: ["print", "signage"],
    },
    {
      id: "studio-6",
      slug: "acrylic-standee-signs",
      title: "Acrylic Standee Signs",
      shortDescription: "Custom acrylic standees for events, retail, and pop-ups.",
      price: 3490,
      image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80",
      category: "Signage",
      categorySlug: "signage",
      tags: ["print", "signage"],
    },
  ],
};

const HAIRCUT_DEMO_TENANT: DemoTenant = {
  slug: "haircut-demo",
  name: "Barber Lane Manila",
  tagline: "Sharp fades, classic cuts, and grooming — book your chair online.",
  category: "Barber & Hair Salons",
  location: "Makati, Metro Manila",
  logoEmoji: "💈",
  patternId: "haircut",
  theme: { primaryColor: "#EB1616", accentColor: "#191C24" },
  shopTheme: {
    templateId: "haircut",
    tier: "standard",
    label: "HairCut Salon",
    layout: "hero-stack",
    header: "standard",
    card: "grid",
    hero: "photo",
    tagline: "Sharp fades, classic cuts, and grooming — book your chair online.",
    promoTitle: "We Will Keep You An Awesome Look",
    promoSubtitle: "Appointments online · Walk-ins welcome · Transparent pricing",
    primaryColor: "#EB1616",
    accentColor: "#191C24",
    background: "#000000",
    foreground: "#ffffff",
    cardBackground: "#191C24",
    muted: "#6C7293",
    border: "#2a2f3a",
    mode: "dark",
    radius: "0",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #000000 0%, #EB1616 55%, #191C24 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0505",
      greeting: "Hi! I'd like to book a haircut appointment:",
    },
  },
  shopCategories: [
    { id: "cuts", name: "Cuts", slug: "cuts" },
    { id: "grooming", name: "Grooming", slug: "grooming" },
    { id: "color", name: "Color", slug: "color" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1600&q=80",
  products: [
    {
      id: "hc-1",
      slug: "signature-fade",
      title: "Signature Fade",
      shortDescription: "Clean skin or mid fade with hot towel finish.",
      price: 350,
      compareAtPrice: 400,
      image: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&q=80",
      category: "Cuts",
      categorySlug: "cuts",
      tags: ["bestseller"],
      isMain: true,
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "hc-2",
      slug: "classic-haircut",
      title: "Classic Haircut",
      shortDescription: "Scissor cut styled to your face shape.",
      price: 300,
      image: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80",
      category: "Cuts",
      categorySlug: "cuts",
      tags: ["popular"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "hc-3",
      slug: "beard-trim",
      title: "Beard Trim",
      shortDescription: "Shape, line-up, and balm for a sharp beard.",
      price: 200,
      image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80",
      category: "Grooming",
      categorySlug: "grooming",
      tags: ["add-on"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "hc-4",
      slug: "hot-shave",
      title: "Hot Towel Shave",
      shortDescription: "Traditional straight-razor shave with aftershave.",
      price: 280,
      image: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
      category: "Grooming",
      categorySlug: "grooming",
      tags: ["classic"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "hc-5",
      slug: "hair-color-refresh",
      title: "Hair Color Refresh",
      shortDescription: "Root touch-up or tone refresh by appointment.",
      price: 1200,
      compareAtPrice: 1500,
      image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
      category: "Color",
      categorySlug: "color",
      tags: ["color"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "hc-6",
      slug: "cut-and-beard-combo",
      title: "Cut & Beard Combo",
      shortDescription: "Haircut plus beard trim — best value package.",
      price: 480,
      compareAtPrice: 550,
      image: "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=800&q=80",
      category: "Cuts",
      categorySlug: "cuts",
      tags: ["package", "bestseller"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
  ],
};

const SPECIALTY_DEMO_TENANT: DemoTenant = {
  slug: "specialty-demo",
  name: "ScreenFix Express",
  tagline: "Same-day phone screen repair — one clear offer, no catalog clutter.",
  category: "Appliance & Device Repair",
  location: "Cebu City",
  logoEmoji: "📱",
  patternId: "specialty",
  theme: { primaryColor: "#0f766e", accentColor: "#134e4a" },
  shopTheme: {
    templateId: "specialty",
    tier: "standard",
    label: "Specialty",
    layout: "hero-stack",
    header: "minimal",
    card: "row",
    hero: "photo",
    tagline: "Same-day phone screen repair — one clear offer, no catalog clutter.",
    promoTitle: "iPhone Screen Replacement",
    promoSubtitle: "Walk-in or book online · Most models done in 45 minutes",
    primaryColor: "#0f766e",
    accentColor: "#134e4a",
    background: "#f4f7f6",
    foreground: "#102a27",
    cardBackground: "#ffffff",
    muted: "#5b726e",
    border: "#d5e0dd",
    mode: "light",
    radius: "0.75rem",
    displayFont: "system",
    previewGradient: "linear-gradient(160deg, #f4f7f6 0%, #0f766e 55%, #134e4a 100%)",
  },
  codEnabled: true,
  subscriptionPlan: "free",
  storeSettings: {
    ...DEFAULT_STOREFRONT_SETTINGS,
    whatsapp: {
      enabled: true,
      phone: "+63 917 555 0606",
      greeting: "Hi! I need a phone repair quote:",
    },
  },
  shopCategories: [
    { id: "repairs", name: "Repairs", slug: "repairs" },
    { id: "add-ons", name: "Add-ons", slug: "add-ons" },
  ],
  coverUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1600&q=80",
  products: [
    {
      id: "sp-1",
      slug: "iphone-screen-replacement",
      title: "iPhone Screen Replacement",
      shortDescription: "OEM-grade glass + LCD/OLED fit for popular iPhone models. Same-day turnaround.",
      price: 2490,
      compareAtPrice: 2990,
      image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80",
      category: "Repairs",
      categorySlug: "repairs",
      tags: ["bestseller", "flagship"],
      isMain: true,
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "sp-2",
      slug: "android-screen-repair",
      title: "Android Screen Repair",
      shortDescription: "Samsung, Xiaomi, Oppo, and Vivo screen jobs — quote by model.",
      price: 1890,
      image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
      category: "Repairs",
      categorySlug: "repairs",
      tags: ["android"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "sp-3",
      slug: "battery-replacement",
      title: "Battery Replacement",
      shortDescription: "Restore all-day battery life with genuine-capacity cells.",
      price: 1290,
      image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
      category: "Repairs",
      categorySlug: "repairs",
      tags: ["battery"],
      pricingMeta: { servicePriceStyle: "base_minimum" },
    },
    {
      id: "sp-4",
      slug: "tempered-glass-install",
      title: "Tempered Glass Install",
      shortDescription: "Premium glass + professional dust-free install after repair.",
      price: 199,
      image: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&q=80",
      category: "Add-ons",
      categorySlug: "add-ons",
      tags: ["addon"],
    },
  ],
};

function demoShopEnabled(): boolean {
  // Demo data must never shadow a real tenant slug in production; enable it
  // explicitly with NEXT_PUBLIC_ENABLE_DEMO_SHOP=true (always on in dev).
  return (
    process.env.NODE_ENV === "development" ||
    process.env.NEXT_PUBLIC_ENABLE_DEMO_SHOP === "true"
  );
}

/** Known live-renderer → demo slug pairs (ops / Template Intel previews). */
const LIVE_TEMPLATE_DEMO_SLUGS: Record<string, string> = {
  bloom: "bloom-demo",
  sarab: "sarab-demo",
  furnish: "furnish-demo",
  zay: "zay-demo",
  electro: "electro-demo",
  kaira: "kaira-demo",
  foodmart: "foodmart-demo",
  stylish: "stylish-demo",
  mellow: "mellow-demo",
  organic: "organic-demo",
  waggy: "waggy-demo",
  fruitables: "fruitables-demo",
  ministore: "ministore-demo",
  aircon: "aircon-demo",
  carserv: "carserv-demo",
  motto: "motto-demo",
  studio: "studio-demo",
  haircut: "haircut-demo",
  specialty: "specialty-demo",
  "simply-sweet": "demo",
  "neon-bazaar": "demo",
  "clean-guma": "demo",
};

export function demoSlugForLiveTemplate(liveTemplateId: string): string {
  return LIVE_TEMPLATE_DEMO_SLUGS[liveTemplateId] ?? "demo";
}

function lookupDemoTenant(slug: string): DemoTenant | null {
  // Live demo + Halo Queen alias → same flagship as `/model` (Simply Sweet kitchen).
  if (slug === "demo" || slug === "haloqueen") {
    return getModelStoreTenant(slug);
  }
  if (slug === "bloom-demo") {
    return BLOOM_DEMO_TENANT;
  }
  if (slug === "sarab-demo") {
    return SARAB_DEMO_TENANT;
  }
  if (slug === "furnish-demo") {
    return FURNISH_DEMO_TENANT;
  }
  if (slug === "zay-demo") {
    return ZAY_DEMO_TENANT;
  }
  if (slug === "electro-demo") {
    return ELECTRO_DEMO_TENANT;
  }
  if (slug === "kaira-demo") {
    return KAIRA_DEMO_TENANT;
  }
  if (slug === "foodmart-demo") {
    return FOODMART_DEMO_TENANT;
  }
  if (slug === "stylish-demo") {
    return STYLISH_DEMO_TENANT;
  }
  if (slug === "mellow-demo") {
    return MELLOW_DEMO_TENANT;
  }
  if (slug === "organic-demo") {
    return ORGANIC_DEMO_TENANT;
  }
  if (slug === "waggy-demo") {
    return WAGGY_DEMO_TENANT;
  }
  if (slug === "fruitables-demo") {
    return FRUITABLES_DEMO_TENANT;
  }
  if (slug === "ministore-demo") {
    return MINISTORE_DEMO_TENANT;
  }
  if (slug === "aircon-demo") {
    return AIRCON_DEMO_TENANT;
  }
  if (slug === "carserv-demo") {
    return CARSERV_DEMO_TENANT;
  }
  if (slug === "motto-demo") {
    return MOTTO_DEMO_TENANT;
  }
  if (slug === "studio-demo") {
    return STUDIO_DEMO_TENANT;
  }
  if (slug === "haircut-demo") {
    return HAIRCUT_DEMO_TENANT;
  }
  if (slug === "specialty-demo") {
    return SPECIALTY_DEMO_TENANT;
  }
  return null;
}

export function getTenant(slug: string): DemoTenant | null {
  if (!demoShopEnabled()) return null;
  return lookupDemoTenant(slug);
}

/**
 * Build a demo tenant for Template Intel stock preview (always available to ops,
 * even when public demo shops are disabled).
 */
export function getOpsStockPreviewTenant(input: {
  liveTemplateId: string;
  label: string;
  categoryLabel: string;
  storeLook?: DemoTenant["shopTheme"]["storeLook"];
  primaryColor?: string;
  accentColor?: string;
  displayFont?: DemoTenant["shopTheme"]["displayFont"];
  radius?: string;
}): DemoTenant | null {
  const slug = demoSlugForLiveTemplate(input.liveTemplateId);
  const base = lookupDemoTenant(slug) ?? lookupDemoTenant("demo");
  if (!base) return null;
  return {
    ...base,
    slug: `ops-preview-${input.liveTemplateId}`,
    name: input.label,
    category: input.categoryLabel,
    tagline: `${input.categoryLabel} · ops stock preview`,
    theme: {
      primaryColor: input.primaryColor ?? base.theme.primaryColor,
      accentColor: input.accentColor ?? base.theme.accentColor,
    },
    shopTheme: {
      ...base.shopTheme,
      templateId: input.liveTemplateId as DemoTenant["shopTheme"]["templateId"],
      tagline: `${input.categoryLabel} · ops stock preview`,
      promoTitle: input.label,
      promoSubtitle: "Template Intel preview — not a live seller shop",
      storeLook: input.storeLook ?? base.shopTheme.storeLook,
      primaryColor: input.primaryColor ?? base.shopTheme.primaryColor,
      accentColor: input.accentColor ?? base.shopTheme.accentColor,
      displayFont: input.displayFont ?? base.shopTheme.displayFont,
      radius: input.radius ?? base.shopTheme.radius,
    },
  };
}

export function getProduct(tenant: DemoTenant, productSlug: string): DemoProduct | undefined {
  return tenant.products.find((p) => p.slug === productSlug);
}

export function getStorefrontUrl(slug: string, path = ""): string {
  const base = process.env.NEXT_PUBLIC_STOREFRONT_URL ?? "http://localhost:3010";
  return `${base}/${slug}${path}`;
}

export function getOrderLink(slug: string, utm?: Record<string, string>): string {
  const url = new URL(getStorefrontUrl(slug));
  if (utm) {
    Object.entries(utm).forEach(([k, v]) => url.searchParams.set(k, v));
  }
  return url.toString();
}
