/**
 * Admin Worker entry: the OpenNext Next.js worker plus a cron dispatcher.
 *
 * Cloudflare's free plan allows 5 cron triggers per account (Kuya Eddie uses
 * one), so wrangler.jsonc has a single every-5-minutes trigger and this file
 * decides which /api/cron/* routes are due at that tick. Each job is an
 * in-process request to this same worker (no network hop) carrying
 * `Authorization: Bearer CRON_SECRET`, exactly like the old Vercel/CT crons.
 */
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import nextWorker from "./.open-next/worker.js";

interface Env {
  CRON_SECRET?: string;
  [key: string]: unknown;
}

interface Job {
  path: string;
  /** Due at this UTC time (the tick is already rounded to 5 minutes). */
  due: (t: Date) => boolean;
}

export const CRON_JOBS: Job[] = [
  // Order events → Inngest (or the event log). Every tick.
  { path: "/api/cron/outbox", due: () => true },
  // Timed SMS: unfinished checkout (30 min / 24 h) + unpaid reminder (6 h). Every tick.
  { path: "/api/cron/automations", due: () => true },
  // Phase 13: Shopee/Lazada — push stock to linked listings, import new paid orders. Every tick.
  { path: "/api/cron/marketplaces", due: () => true },
  // Unpaid orders past each shop's window (1–72 h) → cancelled + restocked. Hourly.
  { path: "/api/cron/expire-orders", due: (t) => t.getUTCMinutes() === 20 },
  // Wallet: release cleared earnings / payouts (no-op while WALLET_PAYOUTS_ENABLED=false). Hourly.
  { path: "/api/cron/wallet-settlement", due: (t) => t.getUTCMinutes() === 40 },
  // AI agents — same times as the old vercel.json (UTC).
  { path: "/api/cron/agent-reminders", due: (t) => t.getUTCHours() === 9 && t.getUTCMinutes() === 0 },
  { path: "/api/cron/agents?mode=daily", due: (t) => t.getUTCHours() === 10 && t.getUTCMinutes() === 0 },
  {
    path: "/api/cron/agents?mode=weekly",
    due: (t) => t.getUTCDay() === 1 && t.getUTCHours() === 2 && t.getUTCMinutes() === 0,
  },
];

export function dueJobs(scheduledTime: number): Job[] {
  const t = new Date(Math.floor(scheduledTime / 300_000) * 300_000);
  return CRON_JOBS.filter((job) => job.due(t));
}

export default {
  fetch: nextWorker.fetch,

  async scheduled(
    controller: { scheduledTime: number; cron: string },
    env: Env,
    ctx: { waitUntil(promise: Promise<unknown>): void }
  ): Promise<void> {
    if (!env.CRON_SECRET) {
      console.error("[cron] CRON_SECRET is not set — skipping all jobs");
      return;
    }
    for (const job of dueJobs(controller.scheduledTime)) {
      try {
        const request = new Request(`https://admin.guma.one${job.path}`, {
          headers: { authorization: `Bearer ${env.CRON_SECRET}`, "user-agent": "gumakart-cron" },
        });
        const response: Response = await nextWorker.fetch(request, env, ctx);
        const body = await response.text();
        if (!response.ok) console.error(`[cron] ${job.path} -> ${response.status} ${body.slice(0, 300)}`);
        else console.log(`[cron] ${job.path} -> ${response.status} ${body.slice(0, 200)}`);
      } catch (error) {
        console.error(`[cron] ${job.path} threw`, error);
      }
    }
  },
};
