/**
 * Admin Worker entry: the OpenNext Next.js worker plus a cron dispatcher.
 *
 * Cloudflare's free plan allows 5 cron triggers per account (Kuya Eddie uses
 * one), so wrangler.jsonc has a single every-minute trigger and lib/cron-schedule.ts
 * decides which /api/cron/* routes are due at that tick. Each job is an
 * in-process request to this same worker (no network hop) carrying
 * `Authorization: Bearer CRON_SECRET`, exactly like the old Vercel/CT crons.
 */
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import nextWorker from "./.open-next/worker.js";
import { CRON_REPORT_PATH, dueJobs, summarizeCronBody } from "./lib/cron-schedule";

interface Env {
  CRON_SECRET?: string;
  [key: string]: unknown;
}

export { CRON_JOBS, dueJobs } from "./lib/cron-schedule";
export default {
  fetch: nextWorker.fetch,

  async scheduled(
    controller: { scheduledTime: number; cron: string },
    env: Env,
    ctx: { waitUntil(promise: Promise<unknown>): void }
  ): Promise<void> {
    if (!env.CRON_SECRET) {
      console.error("[cron] CRON_SECRET is not set — skipping all jobs");
      return;
    }
    const runs: Array<{ job: string; startedAt: string; durationMs: number; ok: boolean; statusCode: number | null; summary: string }> = [];
    const call = (path: string, init?: RequestInit) =>
      nextWorker.fetch(
        new Request(`https://admin.guma.one${path}`, {
          ...init,
          headers: { authorization: `Bearer ${env.CRON_SECRET}`, "user-agent": "gumakart-cron", "content-type": "application/json" },
        }),
        env,
        ctx
      ) as Promise<Response>;
    for (const job of dueJobs(controller.scheduledTime)) {
      const started = Date.now();
      try {
        const response = await call(job.path);
        const body = await response.text();
        runs.push({ job: job.path, startedAt: new Date(started).toISOString(), durationMs: Date.now() - started, ok: response.ok, statusCode: response.status, summary: summarizeCronBody(body) });
        if (!response.ok) console.error(`[cron] ${job.path} -> ${response.status} ${body.slice(0, 300)}`);
      } catch (error) {
        runs.push({ job: job.path, startedAt: new Date(started).toISOString(), durationMs: Date.now() - started, ok: false, statusCode: null, summary: `threw: ${error instanceof Error ? error.message : String(error)}`.slice(0, 300) });
        console.error(`[cron] ${job.path} threw`, error);
      }
    }
    // Phase 16: record the runs and check the alert rules (System health in ops.guma.one).
    try {
      const response = await call(CRON_REPORT_PATH, { method: "POST", body: JSON.stringify({ runs }) });
      if (!response.ok) console.error(`[cron] report -> ${response.status} ${(await response.text()).slice(0, 300)}`);
    } catch (error) {
      console.error("[cron] report threw", error);
    }
  },
};
